# Compare muscle map - whole body model - to ground truth (extended metrics)

Note: this notebook was developed with assistance from Generative AI. The end cross schecks the results against a hand-coded earlier version

In [1]:
# libraries
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import SimpleITK as sitk
from dissector.evaluation import binary_cross_entropy, boundary_iou_3d

In [2]:
!pwd
# above should be about ~something~/~someProjects~/dissector/eval_notebooks/myosegmenTUM

/c/Projects/dissector/eval_notebooks/myosegmenTUM

In [3]:
# dilation distance used for boundary_iou_3d
BOUNDARY_DISTANCE = 1

## Right gracilis

In [4]:
results_r_gracilis = []
for file in os.listdir(os.path.join("..", "MuscleMap_segs")):
    print(file)
    if file[0] == 'H':
        gt_name = file[:7] + "/SegmentationMasks/combined_gt_stack" + file[-13] + ".mha"
    else:
        gt_name = file[:6] + "/SegmentationMasks/combined_gt_stack" + file[-13] + ".mha"
    print(gt_name)

    segment_image = sitk.ReadImage(os.path.join("..", "MuscleMap_segs", file))
    gt_image = sitk.ReadImage(gt_name)
    segment_image.CopyInformation(gt_image)

    gt = sitk.Cast(gt_image == 5, sitk.sitkUInt8)
    pred = sitk.Cast(segment_image == 7152, sitk.sitkUInt8)

    gt_arr = sitk.GetArrayFromImage(gt).astype(float)
    pred_arr = sitk.GetArrayFromImage(pred).astype(float)

    dice_filter = sitk.LabelOverlapMeasuresImageFilter()
    dice_filter.Execute(gt, pred)
    right_grac_dice_lower = dice_filter.GetDiceCoefficient()
    right_JaccardCoeffi = dice_filter.GetJaccardCoefficient()
    right_VolumeSimilar = dice_filter.GetVolumeSimilarity()
    right_FalseNegative = dice_filter.GetFalseNegativeError()
    right_FalsePositive = dice_filter.GetFalsePositiveError()

    hd_filter = sitk.HausdorffDistanceImageFilter()
    hd_filter.Execute(gt, pred)
    right_grac_hd_lower = hd_filter.GetHausdorffDistance()

    bce = binary_cross_entropy(gt_arr, pred_arr)
    biou = boundary_iou_3d(BOUNDARY_DISTANCE, gt_arr, pred_arr)

    results_r_gracilis.append({
        "image": gt_name,
        "pred_label": file,
        "R_gracilis_lower_dice:": right_grac_dice_lower,
        "R_gracilis_lower_Hausdorff:": right_grac_hd_lower,
        "R_gracilis_jaccard": right_JaccardCoeffi,
        "R_gracilis_volume_similarity": right_VolumeSimilar,
        "R_gracilis_falseNegative": right_FalseNegative,
        "R_gracilis_falsePostivie": right_FalsePositive,
        "R_gracilis_binary_cross_entropy": bce,
        "R_gracilis_boundary_iou_3d": biou,
    })

df_r_gracilis = pd.DataFrame(results_r_gracilis)
df_r_gracilis.to_csv('../MuscleMap_results_WB/df_r_gracilis_NEW.csv')
df_r_gracilis

HV001_1_FATFRACTION_stack1_dseg.nii.gz
HV001_1/SegmentationMasks/combined_gt_stack1.mha
HV001_1_FATFRACTION_stack2_dseg.nii.gz
HV001_1/SegmentationMasks/combined_gt_stack2.mha
HV001_2_FATFRACTION_stack1_dseg.nii.gz
HV001_2/SegmentationMasks/combined_gt_stack1.mha
HV001_2_FATFRACTION_stack2_dseg.nii.gz
HV001_2/SegmentationMasks/combined_gt_stack2.mha
HV001_3_FATFRACTION_stack1_dseg.nii.gz
HV001_3/SegmentationMasks/combined_gt_stack1.mha
HV001_3_FATFRACTION_stack2_dseg.nii.gz
HV001_3/SegmentationMasks/combined_gt_stack2.mha
HV002_1_FATFRACTION_stack1_dseg.nii.gz
HV002_1/SegmentationMasks/combined_gt_stack1.mha
HV002_1_FATFRACTION_stack2_dseg.nii.gz
HV002_1/SegmentationMasks/combined_gt_stack2.mha
HV002_2_FATFRACTION_stack1_dseg.nii.gz
HV002_2/SegmentationMasks/combined_gt_stack1.mha
HV002_2_FATFRACTION_stack2_dseg.nii.gz
HV002_2/SegmentationMasks/combined_gt_stack2.mha
HV002_3_FATFRACTION_stack1_dseg.nii.gz
HV002_3/SegmentationMasks/combined_gt_stack1.mha
HV002_3_FATFRACTION_stack2_dseg.nii.gz
HV002_3/SegmentationMasks/combined_gt_stack2.mha
HV003_1_FATFRACTION_stack1_dseg.nii.gz
HV003_1/SegmentationMasks/combined_gt_stack1.mha
HV003_1_FATFRACTION_stack2_dseg.nii.gz
HV003_1/SegmentationMasks/combined_gt_stack2.mha
HV003_2_FATFRACTION_stack1_dseg.nii.gz
HV003_2/SegmentationMasks/combined_gt_stack1.mha
HV003_2_FATFRACTION_stack2_dseg.nii.gz
HV003_2/SegmentationMasks/combined_gt_stack2.mha
HV003_3_FATFRACTION_stack1_dseg.nii.gz
HV003_3/SegmentationMasks/combined_gt_stack1.mha
HV003_3_FATFRACTION_stack2_dseg.nii.gz
HV003_3/SegmentationMasks/combined_gt_stack2.mha
HV004_1_FATFRACTION_stack1_dseg.nii.gz
HV004_1/SegmentationMasks/combined_gt_stack1.mha
HV004_1_FATFRACTION_stack2_dseg.nii.gz
HV004_1/SegmentationMasks/combined_gt_stack2.mha
HV005_1_FATFRACTION_stack1_dseg.nii.gz
HV005_1/SegmentationMasks/combined_gt_stack1.mha
HV005_1_FATFRACTION_stack2_dseg.nii.gz
HV005_1/SegmentationMasks/combined_gt_stack2.mha
HV006_1_FATFRACTION_stack1_dseg.nii.gz
HV006_1/SegmentationMasks/combined_gt_stack1.mha
HV006_1_FATFRACTION_stack2_dseg.nii.gz
HV006_1/SegmentationMasks/combined_gt_stack2.mha
HV007_1_FATFRACTION_stack1_dseg.nii.gz
HV007_1/SegmentationMasks/combined_gt_stack1.mha
HV007_1_FATFRACTION_stack2_dseg.nii.gz
HV007_1/SegmentationMasks/combined_gt_stack2.mha
HV008_1_FATFRACTION_stack1_dseg.nii.gz
HV008_1/SegmentationMasks/combined_gt_stack1.mha
HV008_1_FATFRACTION_stack2_dseg.nii.gz
HV008_1/SegmentationMasks/combined_gt_stack2.mha
HV009_1_FATFRACTION_stack1_dseg.nii.gz
HV009_1/SegmentationMasks/combined_gt_stack1.mha
HV009_1_FATFRACTION_stack2_dseg.nii.gz
HV009_1/SegmentationMasks/combined_gt_stack2.mha
HV010_1_FATFRACTION_stack1_dseg.nii.gz
HV010_1/SegmentationMasks/combined_gt_stack1.mha
HV010_1_FATFRACTION_stack2_dseg.nii.gz
HV010_1/SegmentationMasks/combined_gt_stack2.mha
HV011_1_FATFRACTION_stack1_dseg.nii.gz
HV011_1/SegmentationMasks/combined_gt_stack1.mha
HV011_1_FATFRACTION_stack2_dseg.nii.gz
HV011_1/SegmentationMasks/combined_gt_stack2.mha
HV012_1_FATFRACTION_stack1_dseg.nii.gz
HV012_1/SegmentationMasks/combined_gt_stack1.mha
HV012_1_FATFRACTION_stack2_dseg.nii.gz
HV012_1/SegmentationMasks/combined_gt_stack2.mha
HV013_1_FATFRACTION_stack1_dseg.nii.gz
HV013_1/SegmentationMasks/combined_gt_stack1.mha
HV013_1_FATFRACTION_stack2_dseg.nii.gz
HV013_1/SegmentationMasks/combined_gt_stack2.mha
HV014_1_FATFRACTION_stack1_dseg.nii.gz
HV014_1/SegmentationMasks/combined_gt_stack1.mha
HV014_1_FATFRACTION_stack2_dseg.nii.gz
HV014_1/SegmentationMasks/combined_gt_stack2.mha
HV015_1_FATFRACTION_stack1_dseg.nii.gz
HV015_1/SegmentationMasks/combined_gt_stack1.mha
HV015_1_FATFRACTION_stack2_dseg.nii.gz
HV015_1/SegmentationMasks/combined_gt_stack2.mha
P001_1_FATFRACTION_stack1_dseg.nii.gz
P001_1/SegmentationMasks/combined_gt_stack1.mha
P001_1_FATFRACTION_stack2_dseg.nii.gz
P001_1/SegmentationMasks/combined_gt_stack2.mha
P001_1_FATFRACTION_stack3_dseg.nii.gz
P001_1/SegmentationMasks/combined_gt_stack3.mha
P002_1_FATFRACTION_stack1_dseg.nii.gz
P002_1/SegmentationMasks/combined_gt_stack1.mha
P002_1_FATFRACTION_stack2_dseg.nii.gz
P002_1/SegmentationMasks/combined_gt_stack2.mha
P002_1_FATFRACTION_stack3_dseg.nii.gz
P002_1/SegmentationMasks/combined_gt_stack3.mha
P003_1_FATFRACTION_stack1_dseg.nii.gz
P003_1/SegmentationMasks/combined_gt_stack1.mha
P003_1_FATFRACTION_stack2_dseg.nii.gz
P003_1/SegmentationMasks/combined_gt_stack2.mha
P003_1_FATFRACTION_stack3_dseg.nii.gz
P003_1/SegmentationMasks/combined_gt_stack3.mha
P004_1_FATFRACTION_stack1_dseg.nii.gz
P004_1/SegmentationMasks/combined_gt_stack1.mha
P004_1_FATFRACTION_stack2_dseg.nii.gz
P004_1/SegmentationMasks/combined_gt_stack2.mha
P004_1_FATFRACTION_stack3_dseg.nii.gz
P004_1/SegmentationMasks/combined_gt_stack3.mha

,image,pred_label,R_gracilis_lower_dice:,R_gracilis_lower_Hausdorff:,R_gracilis_jaccard,R_gracilis_volume_similarity,R_gracilis_falseNegative,R_gracilis_falsePostivie,R_gracilis_binary_cross_entropy,R_gracilis_boundary_iou_3d
0,HV001_1/SegmentationMasks/combined_gt_stack1.mha,HV001_1_FATFRACTION_stack1_dseg.nii.gz,0.864141,11.045361,0.760782,-0.070575,0.165313,0.000057,0.002467,0.610530
1,HV001_1/SegmentationMasks/combined_gt_stack2.mha,HV001_1_FATFRACTION_stack2_dseg.nii.gz,0.880848,16.000000,0.787067,-0.020081,0.127908,0.000086,0.003031,0.702395
2,HV001_2/SegmentationMasks/combined_gt_stack1.mha,HV001_2_FATFRACTION_stack1_dseg.nii.gz,0.844484,14.866069,0.730828,-0.096734,0.194477,0.000062,0.002903,0.579530
3,HV001_2/SegmentationMasks/combined_gt_stack2.mha,HV001_2_FATFRACTION_stack2_dseg.nii.gz,0.867442,20.000000,0.765913,-0.084335,0.167656,0.000068,0.003219,0.670560
4,HV001_3/SegmentationMasks/combined_gt_stack1.mha,HV001_3_FATFRACTION_stack1_dseg.nii.gz,0.864027,9.055385,0.760606,-0.052282,0.157984,0.000067,0.002665,0.607997
5,HV001_3/SegmentationMasks/combined_gt_stack2.mha,HV001_3_FATFRACTION_stack2_dseg.nii.gz,0.889236,16.031220,0.800562,0.048875,0.088489,0.000106,0.002806,0.697885
6,HV002_1/SegmentationMasks/combined_gt_stack1.mha,HV002_1_FATFRACTION_stack1_dseg.nii.gz,0.836608,20.248457,0.719111,0.068192,0.133861,0.000171,0.004558,0.554251
7,HV002_1/SegmentationMasks/combined_gt_stack2.mha,HV002_1_FATFRACTION_stack2_dseg.nii.gz,0.873970,24.000000,0.776152,-0.039984,0.143160,0.000077,0.002951,0.663251
8,HV002_2/SegmentationMasks/combined_gt_stack1.mha,HV002_2_FATFRACTION_stack1_dseg.nii.gz,0.855348,18.681542,0.747257,0.044249,0.125299,0.000139,0.003870,0.590948
9,HV002_2/SegmentationMasks/combined_gt_stack2.mha,HV002_2_FATFRACTION_stack2_dseg.nii.gz,0.868235,24.041631,0.767151,0.115447,0.078578,0.000160,0.003588,0.644771
10,HV002_3/SegmentationMasks/combined_gt_stack1.mha,HV002_3_FATFRACTION_stack1_dseg.nii.gz,0.840097,17.549929,0.724282,-0.100430,0.200071,0.000090,0.004230,0.562151
11,HV002_3/SegmentationMasks/combined_gt_stack2.mha,HV002_3_FATFRACTION_stack2_dseg.nii.gz,0.874371,24.103942,0.776784,0.057247,0.099864,0.000120,0.003158,0.653324
12,HV003_1/SegmentationMasks/combined_gt_stack1.mha,HV003_1_FATFRACTION_stack1_dseg.nii.gz,0.853742,22.360680,0.744807,0.128707,0.087538,0.000176,0.003940,0.577152
13,HV003_1/SegmentationMasks/combined_gt_stack2.mha,HV003_1_FATFRACTION_stack2_dseg.nii.gz,0.887382,24.083189,0.797562,0.123799,0.054065,0.000153,0.003178,0.652359
14,HV003_2/SegmentationMasks/combined_gt_stack1.mha,HV003_2_FATFRACTION_stack1_dseg.nii.gz,0.866999,12.165525,0.765224,0.141577,0.066952,0.000180,0.003790,0.585233
15,HV003_2/SegmentationMasks/combined_gt_stack2.mha,HV003_2_FATFRACTION_stack2_dseg.nii.gz,0.897668,20.099751,0.814335,0.129938,0.039960,0.000148,0.002911,0.672448
16,HV003_3/SegmentationMasks/combined_gt_stack1.mha,HV003_3_FATFRACTION_stack1_dseg.nii.gz,0.853384,10.049876,0.744264,0.173300,0.065655,0.000201,0.004076,0.551854
17,HV003_3/SegmentationMasks/combined_gt_stack2.mha,HV003_3_FATFRACTION_stack2_dseg.nii.gz,0.884630,28.017851,0.793127,0.144913,0.046266,0.000171,0.003384,0.645430
18,HV004_1/SegmentationMasks/combined_gt_stack1.mha,HV004_1_FATFRACTION_stack1_dseg.nii.gz,0.873810,10.677078,0.775900,0.074721,0.092277,0.000075,0.001857,0.689001
19,HV004_1/SegmentationMasks/combined_gt_stack2.mha,HV004_1_FATFRACTION_stack2_dseg.nii.gz,0.893368,20.099751,0.807286,0.023139,0.096175,0.000049,0.001414,0.751729
20,HV005_1/SegmentationMasks/combined_gt_stack1.mha,HV005_1_FATFRACTION_stack1_dseg.nii.gz,0.854804,7.071068,0.746426,-0.005071,0.147358,0.000092,0.003019,0.612646
21,HV005_1/SegmentationMasks/combined_gt_stack2.mha,HV005_1_FATFRACTION_stack2_dseg.nii.gz,0.867030,40.311289,0.765272,-0.028241,0.145042,0.000073,0.002643,0.655873
22,HV006_1/SegmentationMasks/combined_gt_stack1.mha,HV006_1_FATFRACTION_stack1_dseg.nii.gz,0.875903,9.219544,0.779206,0.005789,0.121554,0.000083,0.002613,0.609433
23,HV006_1/SegmentationMasks/combined_gt_stack2.mha,HV006_1_FATFRACTION_stack2_dseg.nii.gz,0.890950,12.369317,0.803346,0.007649,0.105629,0.000107,0.003337,0.688694
24,HV007_1/SegmentationMasks/combined_gt_stack1.mha,HV007_1_FATFRACTION_stack1_dseg.nii.gz,0.882372,10.816654,0.789504,-0.013416,0.123508,0.000100,0.003418,0.601662
25,HV007_1/SegmentationMasks/combined_gt_stack2.mha,HV007_1_FATFRACTION_stack2_dseg.nii.gz,0.861855,24.413111,0.757245,0.032525,0.123897,0.000132,0.003802,0.595748
26,HV008_1/SegmentationMasks/combined_gt_stack1.mha,HV008_1_FATFRACTION_stack1_dseg.nii.gz,0.888543,5.830952,0.799440,0.045309,0.090861,0.000106,0.002831,0.655567
27,HV008_1/SegmentationMasks/combined_gt_stack2.mha,HV008_1_FATFRACTION_stack2_dseg.nii.gz,0.884022,20.248457,0.792149,0.025421,0.104597,0.000072,0.002085,0.701664
28,HV009_1/SegmentationMasks/combined_gt_stack1.mha,HV009_1_FATFRACTION_stack1_dseg.nii.gz,0.823265,29.966648,0.699618,-0.026302,0.187421,0.000092,0.003195,0.554164
29,HV009_1/SegmentationMasks/combined_gt_stack2.mha,HV009_1_FATFRACTION_stack2_dseg.nii.gz,0.863967,7.810250,0.760512,-0.011369,0.140917,0.000073,0.002441,0.690417
30,HV010_1/SegmentationMasks/combined_gt_stack1.mha,HV010_1_FATFRACTION_stack1_dseg.nii.gz,0.870252,12.041595,0.770306,0.008880,0.125867,0.000042,0.001300,0.675052
31,HV010_1/SegmentationMasks/combined_gt_stack2.mha,HV010_1_FATFRACTION_stack2_dseg.nii.gz,0.853489,28.017851,0.744423,-0.021150,0.155442,0.000074,0.002564,0.680043
32,HV011_1/SegmentationMasks/combined_gt_stack1.mha,HV011_1_FATFRACTION_stack1_dseg.nii.gz,0.860814,12.041595,0.755640,0.030472,0.125867,0.000049,0.001410,0.655738
33,HV011_1/SegmentationMasks/combined_gt_stack2.mha,HV011_1_FATFRACTION_stack2_dseg.nii.gz,0.838202,24.020824,0.721470,-0.009888,0.165921,0.000086,0.002847,0.653571
34,HV012_1/SegmentationMasks/combined_gt_stack1.mha,HV012_1_FATFRACTION_stack1_dseg.nii.gz,0.524480,16.763055,0.355454,-0.771114,0.621466,0.000015,0.002485,0.379803
35,HV012_1/SegmentationMasks/combined_gt_stack2.mha,HV012_1_FATFRACTION_stack2_dseg.nii.gz,0.564573,12.083046,0.393314,-0.848620,0.603616,0.000006,0.007515,0.392953
36,HV013_1/SegmentationMasks/combined_gt_stack1.mha,HV013_1_FATFRACTION_stack1_dseg.nii.gz,0.752900,16.763055,0.603721,-0.422165,0.378324,0.000021,0.004564,0.480538
37,HV013_1/SegmentationMasks/combined_gt_stack2.mha,HV013_1_FATFRACTION_stack2_dseg.nii.gz,0.813065,12.000000,0.685012,-0.274272,0.284989,0.000052,0.006315,0.622778
38,HV014_1/SegmentationMasks/combined_gt_stack1.mha,HV014_1_FATFRACTION_stack1_dseg.nii.gz,0.587609,20.493902,0.416039,-0.807580,0.581412,0.000006,0.009047,0.340064
39,HV014_1/SegmentationMasks/combined_gt_stack2.mha,HV014_1_FATFRACTION_stack2_dseg.nii.gz,0.550059,32.526912,0.379367,-0.721256,0.595731,0.000053,0.008523,0.439161
40,HV015_1/SegmentationMasks/combined_gt_stack1.mha,HV015_1_FATFRACTION_stack1_dseg.nii.gz,0.667257,12.649111,0.500664,-0.610607,0.488811,0.000018,0.007213,0.399174
41,HV015_1/SegmentationMasks/combined_gt_stack2.mha,HV015_1_FATFRACTION_stack2_dseg.nii.gz,0.711508,12.000000,0.552202,-0.411262,0.409846,0.000097,0.010912,0.481052
42,P001_1/SegmentationMasks/combined_gt_stack1.mha,P001_1_FATFRACTION_stack1_dseg.nii.gz,0.814462,13.152946,0.686998,-0.265674,0.281042,0.000105,0.011906,0.565184
43,P001_1/SegmentationMasks/combined_gt_stack2.mha,P001_1_FATFRACTION_stack2_dseg.nii.gz,0.874351,4.582576,0.776752,-0.096615,0.165940,0.000158,0.008231,0.647146
44,P001_1/SegmentationMasks/combined_gt_stack3.mha,P001_1_FATFRACTION_stack3_dseg.nii.gz,0.615238,5.385165,0.444291,-0.736813,0.550398,0.000008,0.005786,0.359751
45,P002_1/SegmentationMasks/combined_gt_stack1.mha,P002_1_FATFRACTION_stack1_dseg.nii.gz,0.730533,4.000000,0.575465,-0.528551,0.422172,0.000003,0.004681,0.457902
46,P002_1/SegmentationMasks/combined_gt_stack2.mha,P002_1_FATFRACTION_stack2_dseg.nii.gz,0.876268,5.000000,0.779784,-0.223858,0.211939,0.000027,0.009024,0.576979
47,P002_1/SegmentationMasks/combined_gt_stack3.mha,P002_1_FATFRACTION_stack3_dseg.nii.gz,0.787232,4.242641,0.649120,-0.414401,0.347886,0.000004,0.004700,0.476830
48,P003_1/SegmentationMasks/combined_gt_stack1.mha,P003_1_FATFRACTION_stack1_dseg.nii.gz,0.648627,9.165151,0.479977,-0.689569,0.517672,0.000005,0.009182,0.394268
49,P003_1/SegmentationMasks/combined_gt_stack2.mha,P003_1_FATFRACTION_stack2_dseg.nii.gz,0.764458,5.099020,0.618723,-0.461268,0.378810,0.000007,0.010426,0.470527
50,P003_1/SegmentationMasks/combined_gt_stack3.mha,P003_1_FATFRACTION_stack3_dseg.nii.gz,0.731580,8.602325,0.576765,-0.533123,0.422388,0.000001,0.005921,0.455968
51,P004_1/SegmentationMasks/combined_gt_stack1.mha,P004_1_FATFRACTION_stack1_dseg.nii.gz,0.834543,6.164414,0.716065,-0.226875,0.250481,0.000071,0.007288,0.589266
52,P004_1/SegmentationMasks/combined_gt_stack2.mha,P004_1_FATFRACTION_stack2_dseg.nii.gz,0.823305,4.582576,0.699676,-0.313207,0.288170,0.000024,0.006850,0.523652
53,P004_1/SegmentationMasks/combined_gt_stack3.mha,P004_1_FATFRACTION_stack3_dseg.nii.gz,0.114050,9.219544,0.060473,-1.771901,0.939527,0.000000,0.002197,0.130358

## Left gracilis

In [5]:
results_l_gracilis = []
for file in os.listdir(os.path.join("..", "MuscleMap_segs")):
    print(file)
    if file[0] == 'H':
        gt_name = file[:7] + "/SegmentationMasks/combined_gt_stack" + file[-13] + ".mha"
    else:
        gt_name = file[:6] + "/SegmentationMasks/combined_gt_stack" + file[-13] + ".mha"
    print(gt_name)

    segment_image = sitk.ReadImage(os.path.join("..", "MuscleMap_segs", file))
    gt_image = sitk.ReadImage(gt_name)
    segment_image.CopyInformation(gt_image)

    gt = sitk.Cast(gt_image == 1, sitk.sitkUInt8)
    pred = sitk.Cast(segment_image == 7151, sitk.sitkUInt8)

    gt_arr = sitk.GetArrayFromImage(gt).astype(float)
    pred_arr = sitk.GetArrayFromImage(pred).astype(float)

    dice_filter = sitk.LabelOverlapMeasuresImageFilter()
    dice_filter.Execute(gt, pred)
    left_grac_dice_lower = dice_filter.GetDiceCoefficient()
    left_JaccardCoeffi = dice_filter.GetJaccardCoefficient()
    left_VolumeSimilar = dice_filter.GetVolumeSimilarity()
    left_FalseNegative = dice_filter.GetFalseNegativeError()
    left_FalsePositive = dice_filter.GetFalsePositiveError()

    hd_filter = sitk.HausdorffDistanceImageFilter()
    hd_filter.Execute(gt, pred)
    left_grac_hd_lower = hd_filter.GetHausdorffDistance()

    bce = binary_cross_entropy(gt_arr, pred_arr)
    biou = boundary_iou_3d(BOUNDARY_DISTANCE, gt_arr, pred_arr)

    results_l_gracilis.append({
        "image": gt_name,
        "pred_label": file,
        "L_gracilis_lower_dice:": left_grac_dice_lower,
        "L_gracilis_lower_Hausdorff:": left_grac_hd_lower,
        "L_gracilis_jaccard": left_JaccardCoeffi,
        "L_gracilis_volume_similarity": left_VolumeSimilar,
        "L_gracilis_falseNegative": left_FalseNegative,
        "L_gracilis_falsePostivie": left_FalsePositive,
        "L_gracilis_binary_cross_entropy": bce,
        "L_gracilis_boundary_iou_3d": biou,
    })

df_l_gracilis = pd.DataFrame(results_l_gracilis)
df_l_gracilis.to_csv('../MuscleMap_results_WB/df_l_gracilis_NEW.csv')
df_l_gracilis

HV001_1_FATFRACTION_stack1_dseg.nii.gz
HV001_1/SegmentationMasks/combined_gt_stack1.mha
HV001_1_FATFRACTION_stack2_dseg.nii.gz
HV001_1/SegmentationMasks/combined_gt_stack2.mha
HV001_2_FATFRACTION_stack1_dseg.nii.gz
HV001_2/SegmentationMasks/combined_gt_stack1.mha
HV001_2_FATFRACTION_stack2_dseg.nii.gz
HV001_2/SegmentationMasks/combined_gt_stack2.mha
HV001_3_FATFRACTION_stack1_dseg.nii.gz
HV001_3/SegmentationMasks/combined_gt_stack1.mha
HV001_3_FATFRACTION_stack2_dseg.nii.gz
HV001_3/SegmentationMasks/combined_gt_stack2.mha
HV002_1_FATFRACTION_stack1_dseg.nii.gz
HV002_1/SegmentationMasks/combined_gt_stack1.mha
HV002_1_FATFRACTION_stack2_dseg.nii.gz
HV002_1/SegmentationMasks/combined_gt_stack2.mha
HV002_2_FATFRACTION_stack1_dseg.nii.gz
HV002_2/SegmentationMasks/combined_gt_stack1.mha
HV002_2_FATFRACTION_stack2_dseg.nii.gz
HV002_2/SegmentationMasks/combined_gt_stack2.mha
HV002_3_FATFRACTION_stack1_dseg.nii.gz
HV002_3/SegmentationMasks/combined_gt_stack1.mha
HV002_3_FATFRACTION_stack2_dseg.nii.gz
HV002_3/SegmentationMasks/combined_gt_stack2.mha
HV003_1_FATFRACTION_stack1_dseg.nii.gz
HV003_1/SegmentationMasks/combined_gt_stack1.mha
HV003_1_FATFRACTION_stack2_dseg.nii.gz
HV003_1/SegmentationMasks/combined_gt_stack2.mha
HV003_2_FATFRACTION_stack1_dseg.nii.gz
HV003_2/SegmentationMasks/combined_gt_stack1.mha
HV003_2_FATFRACTION_stack2_dseg.nii.gz
HV003_2/SegmentationMasks/combined_gt_stack2.mha
HV003_3_FATFRACTION_stack1_dseg.nii.gz
HV003_3/SegmentationMasks/combined_gt_stack1.mha
HV003_3_FATFRACTION_stack2_dseg.nii.gz
HV003_3/SegmentationMasks/combined_gt_stack2.mha
HV004_1_FATFRACTION_stack1_dseg.nii.gz
HV004_1/SegmentationMasks/combined_gt_stack1.mha
HV004_1_FATFRACTION_stack2_dseg.nii.gz
HV004_1/SegmentationMasks/combined_gt_stack2.mha
HV005_1_FATFRACTION_stack1_dseg.nii.gz
HV005_1/SegmentationMasks/combined_gt_stack1.mha
HV005_1_FATFRACTION_stack2_dseg.nii.gz
HV005_1/SegmentationMasks/combined_gt_stack2.mha
HV006_1_FATFRACTION_stack1_dseg.nii.gz
HV006_1/SegmentationMasks/combined_gt_stack1.mha
HV006_1_FATFRACTION_stack2_dseg.nii.gz
HV006_1/SegmentationMasks/combined_gt_stack2.mha
HV007_1_FATFRACTION_stack1_dseg.nii.gz
HV007_1/SegmentationMasks/combined_gt_stack1.mha
HV007_1_FATFRACTION_stack2_dseg.nii.gz
HV007_1/SegmentationMasks/combined_gt_stack2.mha
HV008_1_FATFRACTION_stack1_dseg.nii.gz
HV008_1/SegmentationMasks/combined_gt_stack1.mha
HV008_1_FATFRACTION_stack2_dseg.nii.gz
HV008_1/SegmentationMasks/combined_gt_stack2.mha
HV009_1_FATFRACTION_stack1_dseg.nii.gz
HV009_1/SegmentationMasks/combined_gt_stack1.mha
HV009_1_FATFRACTION_stack2_dseg.nii.gz
HV009_1/SegmentationMasks/combined_gt_stack2.mha
HV010_1_FATFRACTION_stack1_dseg.nii.gz
HV010_1/SegmentationMasks/combined_gt_stack1.mha
HV010_1_FATFRACTION_stack2_dseg.nii.gz
HV010_1/SegmentationMasks/combined_gt_stack2.mha
HV011_1_FATFRACTION_stack1_dseg.nii.gz
HV011_1/SegmentationMasks/combined_gt_stack1.mha
HV011_1_FATFRACTION_stack2_dseg.nii.gz
HV011_1/SegmentationMasks/combined_gt_stack2.mha
HV012_1_FATFRACTION_stack1_dseg.nii.gz
HV012_1/SegmentationMasks/combined_gt_stack1.mha
HV012_1_FATFRACTION_stack2_dseg.nii.gz
HV012_1/SegmentationMasks/combined_gt_stack2.mha
HV013_1_FATFRACTION_stack1_dseg.nii.gz
HV013_1/SegmentationMasks/combined_gt_stack1.mha
HV013_1_FATFRACTION_stack2_dseg.nii.gz
HV013_1/SegmentationMasks/combined_gt_stack2.mha
HV014_1_FATFRACTION_stack1_dseg.nii.gz
HV014_1/SegmentationMasks/combined_gt_stack1.mha
HV014_1_FATFRACTION_stack2_dseg.nii.gz
HV014_1/SegmentationMasks/combined_gt_stack2.mha
HV015_1_FATFRACTION_stack1_dseg.nii.gz
HV015_1/SegmentationMasks/combined_gt_stack1.mha
HV015_1_FATFRACTION_stack2_dseg.nii.gz
HV015_1/SegmentationMasks/combined_gt_stack2.mha
P001_1_FATFRACTION_stack1_dseg.nii.gz
P001_1/SegmentationMasks/combined_gt_stack1.mha
P001_1_FATFRACTION_stack2_dseg.nii.gz
P001_1/SegmentationMasks/combined_gt_stack2.mha
P001_1_FATFRACTION_stack3_dseg.nii.gz
P001_1/SegmentationMasks/combined_gt_stack3.mha
P002_1_FATFRACTION_stack1_dseg.nii.gz
P002_1/SegmentationMasks/combined_gt_stack1.mha
P002_1_FATFRACTION_stack2_dseg.nii.gz
P002_1/SegmentationMasks/combined_gt_stack2.mha
P002_1_FATFRACTION_stack3_dseg.nii.gz
P002_1/SegmentationMasks/combined_gt_stack3.mha
P003_1_FATFRACTION_stack1_dseg.nii.gz
P003_1/SegmentationMasks/combined_gt_stack1.mha
P003_1_FATFRACTION_stack2_dseg.nii.gz
P003_1/SegmentationMasks/combined_gt_stack2.mha
P003_1_FATFRACTION_stack3_dseg.nii.gz
P003_1/SegmentationMasks/combined_gt_stack3.mha
P004_1_FATFRACTION_stack1_dseg.nii.gz
P004_1/SegmentationMasks/combined_gt_stack1.mha
P004_1_FATFRACTION_stack2_dseg.nii.gz
P004_1/SegmentationMasks/combined_gt_stack2.mha
P004_1_FATFRACTION_stack3_dseg.nii.gz
P004_1/SegmentationMasks/combined_gt_stack3.mha

,image,pred_label,L_gracilis_lower_dice:,L_gracilis_lower_Hausdorff:,L_gracilis_jaccard,L_gracilis_volume_similarity,L_gracilis_falseNegative,L_gracilis_falsePostivie,L_gracilis_binary_cross_entropy,L_gracilis_boundary_iou_3d
0,HV001_1/SegmentationMasks/combined_gt_stack1.mha,HV001_1_FATFRACTION_stack1_dseg.nii.gz,0.847848,8.306624,0.735882,-0.021016,0.160969,6.707813e-05,0.002322,0.594375
1,HV001_1/SegmentationMasks/combined_gt_stack2.mha,HV001_1_FATFRACTION_stack2_dseg.nii.gz,0.840353,12.206556,0.724663,0.014421,0.153543,1.215557e-04,0.003747,0.646513
2,HV001_2/SegmentationMasks/combined_gt_stack1.mha,HV001_2_FATFRACTION_stack1_dseg.nii.gz,0.858697,6.403124,0.752383,-0.063328,0.167658,5.358208e-05,0.002225,0.630302
3,HV001_2/SegmentationMasks/combined_gt_stack2.mha,HV001_2_FATFRACTION_stack2_dseg.nii.gz,0.828016,20.199010,0.706508,0.066260,0.143612,1.478659e-04,0.003994,0.630639
4,HV001_3/SegmentationMasks/combined_gt_stack1.mha,HV001_3_FATFRACTION_stack1_dseg.nii.gz,0.835699,8.124038,0.717769,-0.042314,0.181616,7.287550e-05,0.002695,0.576947
5,HV001_3/SegmentationMasks/combined_gt_stack2.mha,HV001_3_FATFRACTION_stack2_dseg.nii.gz,0.827036,16.248077,0.705083,-0.030429,0.185358,1.063817e-04,0.003758,0.622553
6,HV002_1/SegmentationMasks/combined_gt_stack1.mha,HV002_1_FATFRACTION_stack1_dseg.nii.gz,0.828220,26.832816,0.706805,0.053324,0.149093,1.498394e-04,0.004178,0.569621
7,HV002_1/SegmentationMasks/combined_gt_stack2.mha,HV002_1_FATFRACTION_stack2_dseg.nii.gz,0.810118,24.020824,0.680839,0.177269,0.111094,1.978321e-04,0.004345,0.562935
8,HV002_2/SegmentationMasks/combined_gt_stack1.mha,HV002_2_FATFRACTION_stack1_dseg.nii.gz,0.843304,20.639767,0.729062,0.085814,0.118891,1.476535e-04,0.003734,0.575537
9,HV002_2/SegmentationMasks/combined_gt_stack2.mha,HV002_2_FATFRACTION_stack2_dseg.nii.gz,0.825252,24.000000,0.702493,0.149547,0.108054,1.920028e-04,0.004332,0.585631
10,HV002_3/SegmentationMasks/combined_gt_stack1.mha,HV002_3_FATFRACTION_stack1_dseg.nii.gz,0.822905,22.203603,0.699098,0.132036,0.118928,1.874414e-04,0.004398,0.559196
11,HV002_3/SegmentationMasks/combined_gt_stack2.mha,HV002_3_FATFRACTION_stack2_dseg.nii.gz,0.799270,18.138357,0.665653,0.187482,0.118056,2.018522e-04,0.004433,0.533181
12,HV003_1/SegmentationMasks/combined_gt_stack1.mha,HV003_1_FATFRACTION_stack1_dseg.nii.gz,0.860442,21.954498,0.755066,0.152408,0.068580,1.889241e-04,0.003936,0.595213
13,HV003_1/SegmentationMasks/combined_gt_stack2.mha,HV003_1_FATFRACTION_stack2_dseg.nii.gz,0.861113,20.049938,0.756101,0.146962,0.070593,1.826906e-04,0.003849,0.635344
14,HV003_2/SegmentationMasks/combined_gt_stack1.mha,HV003_2_FATFRACTION_stack1_dseg.nii.gz,0.871045,19.646883,0.771550,0.107010,0.079715,1.604580e-04,0.003653,0.616544
15,HV003_2/SegmentationMasks/combined_gt_stack2.mha,HV003_2_FATFRACTION_stack2_dseg.nii.gz,0.868981,20.322401,0.768317,0.153343,0.058860,1.776815e-04,0.003611,0.640821
16,HV003_3/SegmentationMasks/combined_gt_stack1.mha,HV003_3_FATFRACTION_stack1_dseg.nii.gz,0.873149,14.456832,0.774858,0.126383,0.067953,1.663205e-04,0.003576,0.611941
17,HV003_3/SegmentationMasks/combined_gt_stack2.mha,HV003_3_FATFRACTION_stack2_dseg.nii.gz,0.872159,20.420578,0.773300,0.160932,0.051521,1.865251e-04,0.003687,0.644087
18,HV004_1/SegmentationMasks/combined_gt_stack1.mha,HV004_1_FATFRACTION_stack1_dseg.nii.gz,0.842237,9.000000,0.727470,-0.065849,0.184609,5.085101e-05,0.002071,0.655386
19,HV004_1/SegmentationMasks/combined_gt_stack2.mha,HV004_1_FATFRACTION_stack2_dseg.nii.gz,0.864217,24.103942,0.760899,0.001670,0.135061,5.619459e-05,0.001800,0.701044
20,HV005_1/SegmentationMasks/combined_gt_stack1.mha,HV005_1_FATFRACTION_stack1_dseg.nii.gz,0.876601,12.041595,0.780312,0.084096,0.084921,1.232782e-04,0.002962,0.644347
21,HV005_1/SegmentationMasks/combined_gt_stack2.mha,HV005_1_FATFRACTION_stack2_dseg.nii.gz,0.847379,32.140317,0.735175,0.183199,0.067175,1.799673e-04,0.003623,0.609782
22,HV006_1/SegmentationMasks/combined_gt_stack1.mha,HV006_1_FATFRACTION_stack1_dseg.nii.gz,0.866490,8.000000,0.764431,0.028041,0.121189,9.200638e-05,0.002683,0.596328
23,HV006_1/SegmentationMasks/combined_gt_stack2.mha,HV006_1_FATFRACTION_stack2_dseg.nii.gz,0.891334,16.031220,0.803969,0.066120,0.078191,1.239764e-04,0.003062,0.691280
24,HV007_1/SegmentationMasks/combined_gt_stack1.mha,HV007_1_FATFRACTION_stack1_dseg.nii.gz,0.838013,8.246211,0.721190,-0.134985,0.214970,5.982995e-05,0.003304,0.542921
25,HV007_1/SegmentationMasks/combined_gt_stack2.mha,HV007_1_FATFRACTION_stack2_dseg.nii.gz,0.879244,16.492423,0.784510,-0.003507,0.122295,7.328891e-05,0.002396,0.692467
26,HV008_1/SegmentationMasks/combined_gt_stack1.mha,HV008_1_FATFRACTION_stack1_dseg.nii.gz,0.819093,10.246951,0.693613,0.186447,0.096699,1.982360e-04,0.004215,0.547713
27,HV008_1/SegmentationMasks/combined_gt_stack2.mha,HV008_1_FATFRACTION_stack2_dseg.nii.gz,0.846113,20.024984,0.733272,0.051592,0.131483,9.915060e-05,0.002736,0.625537
28,HV009_1/SegmentationMasks/combined_gt_stack1.mha,HV009_1_FATFRACTION_stack1_dseg.nii.gz,0.826998,13.038405,0.705027,0.042911,0.154870,1.048829e-04,0.003006,0.573025
29,HV009_1/SegmentationMasks/combined_gt_stack2.mha,HV009_1_FATFRACTION_stack2_dseg.nii.gz,0.851636,9.000000,0.741608,0.007958,0.144962,8.457382e-05,0.002654,0.659284
30,HV010_1/SegmentationMasks/combined_gt_stack1.mha,HV010_1_FATFRACTION_stack1_dseg.nii.gz,0.828219,12.041595,0.706803,-0.131129,0.222742,3.196614e-05,0.001666,0.611310
31,HV010_1/SegmentationMasks/combined_gt_stack2.mha,HV010_1_FATFRACTION_stack2_dseg.nii.gz,0.824043,16.309506,0.700743,0.095633,0.134575,1.219726e-04,0.003090,0.608135
32,HV011_1/SegmentationMasks/combined_gt_stack1.mha,HV011_1_FATFRACTION_stack1_dseg.nii.gz,0.804588,12.083046,0.673064,0.064091,0.168775,7.534875e-05,0.002086,0.556698
33,HV011_1/SegmentationMasks/combined_gt_stack2.mha,HV011_1_FATFRACTION_stack2_dseg.nii.gz,0.817722,20.223748,0.691650,0.107317,0.135912,1.293842e-04,0.003221,0.595435
34,HV012_1/SegmentationMasks/combined_gt_stack1.mha,HV012_1_FATFRACTION_stack1_dseg.nii.gz,0.657738,16.031220,0.490022,-0.627330,0.499311,7.840124e-06,0.003024,0.416845
35,HV012_1/SegmentationMasks/combined_gt_stack2.mha,HV012_1_FATFRACTION_stack2_dseg.nii.gz,0.710018,5.656854,0.550409,-0.548942,0.442892,2.017227e-05,0.012137,0.375113
36,HV013_1/SegmentationMasks/combined_gt_stack1.mha,HV013_1_FATFRACTION_stack1_dseg.nii.gz,0.821020,4.242641,0.696382,-0.262465,0.274225,3.256479e-05,0.003932,0.575561
37,HV013_1/SegmentationMasks/combined_gt_stack2.mha,HV013_1_FATFRACTION_stack2_dseg.nii.gz,0.779724,12.083046,0.638974,-0.163369,0.279158,1.516674e-04,0.007762,0.556591
38,HV014_1/SegmentationMasks/combined_gt_stack1.mha,HV014_1_FATFRACTION_stack1_dseg.nii.gz,0.591572,24.207437,0.420023,-0.788815,0.575754,8.737745e-06,0.008198,0.372098
39,HV014_1/SegmentationMasks/combined_gt_stack2.mha,HV014_1_FATFRACTION_stack2_dseg.nii.gz,0.659606,14.594520,0.492099,-0.473477,0.466657,5.489704e-05,0.005808,0.571277
40,HV015_1/SegmentationMasks/combined_gt_stack1.mha,HV015_1_FATFRACTION_stack1_dseg.nii.gz,0.600518,12.409674,0.429100,-0.728152,0.559762,2.035325e-05,0.007397,0.374910
41,HV015_1/SegmentationMasks/combined_gt_stack2.mha,HV015_1_FATFRACTION_stack2_dseg.nii.gz,0.607965,20.322401,0.436746,-0.629934,0.537657,6.515171e-05,0.010672,0.442580
42,P001_1/SegmentationMasks/combined_gt_stack1.mha,P001_1_FATFRACTION_stack1_dseg.nii.gz,0.806296,11.575837,0.675457,-0.302198,0.299542,9.177976e-05,0.013418,0.540420
43,P001_1/SegmentationMasks/combined_gt_stack2.mha,P001_1_FATFRACTION_stack2_dseg.nii.gz,0.871031,6.082763,0.771527,0.011590,0.123892,2.904107e-04,0.008940,0.696819
44,P001_1/SegmentationMasks/combined_gt_stack3.mha,P001_1_FATFRACTION_stack3_dseg.nii.gz,0.692271,6.324555,0.529368,-0.547826,0.456579,1.781387e-05,0.005222,0.454442
45,P002_1/SegmentationMasks/combined_gt_stack1.mha,P002_1_FATFRACTION_stack1_dseg.nii.gz,0.762408,4.242641,0.616042,-0.465291,0.381486,3.690933e-06,0.005710,0.479252
46,P002_1/SegmentationMasks/combined_gt_stack2.mha,P002_1_FATFRACTION_stack2_dseg.nii.gz,0.812115,5.830952,0.683664,-0.375393,0.316227,6.383404e-07,0.020432,0.341410
47,P002_1/SegmentationMasks/combined_gt_stack3.mha,P002_1_FATFRACTION_stack3_dseg.nii.gz,0.852108,3.741657,0.742324,-0.290318,0.255905,2.418423e-06,0.004214,0.572947
48,P003_1/SegmentationMasks/combined_gt_stack1.mha,P003_1_FATFRACTION_stack1_dseg.nii.gz,0.742486,6.082763,0.590440,-0.501762,0.406430,6.110549e-06,0.007639,0.483482
49,P003_1/SegmentationMasks/combined_gt_stack2.mha,P003_1_FATFRACTION_stack2_dseg.nii.gz,0.773347,5.000000,0.630453,-0.228861,0.306061,1.650651e-04,0.010729,0.489382
50,P003_1/SegmentationMasks/combined_gt_stack3.mha,P003_1_FATFRACTION_stack3_dseg.nii.gz,0.647169,11.401754,0.478381,-0.701255,0.520839,1.654712e-06,0.008530,0.355171
51,P004_1/SegmentationMasks/combined_gt_stack1.mha,P004_1_FATFRACTION_stack1_dseg.nii.gz,0.812812,5.000000,0.684654,-0.357585,0.310471,1.069720e-05,0.007678,0.544450
52,P004_1/SegmentationMasks/combined_gt_stack2.mha,P004_1_FATFRACTION_stack2_dseg.nii.gz,0.828410,5.385165,0.707082,-0.327520,0.288161,9.805326e-06,0.006917,0.534358
53,P004_1/SegmentationMasks/combined_gt_stack3.mha,P004_1_FATFRACTION_stack3_dseg.nii.gz,0.073363,9.055385,0.038079,-1.853273,0.961921,0.000000e+00,0.003365,0.093541

## Right sartorius

In [6]:
results_r_sart = []
for file in os.listdir(os.path.join("..", "MuscleMap_segs")):
    print(file)
    if file[0] == 'H':
        gt_name = file[:7] + "/SegmentationMasks/combined_gt_stack" + file[-13] + ".mha"
    else:
        gt_name = file[:6] + "/SegmentationMasks/combined_gt_stack" + file[-13] + ".mha"
    print(gt_name)

    segment_image = sitk.ReadImage(os.path.join("..", "MuscleMap_segs", file))
    gt_image = sitk.ReadImage(gt_name)
    segment_image.CopyInformation(gt_image)

    gt = sitk.Cast(gt_image == 8, sitk.sitkUInt8)
    pred = sitk.Cast(segment_image == 7142, sitk.sitkUInt8)

    gt_arr = sitk.GetArrayFromImage(gt).astype(float)
    pred_arr = sitk.GetArrayFromImage(pred).astype(float)

    dice_filter = sitk.LabelOverlapMeasuresImageFilter()
    dice_filter.Execute(gt, pred)
    right_sart_dice_lower = dice_filter.GetDiceCoefficient()
    right_JaccardCoeffi = dice_filter.GetJaccardCoefficient()
    right_VolumeSimilar = dice_filter.GetVolumeSimilarity()
    right_FalseNegative = dice_filter.GetFalseNegativeError()
    right_FalsePositive = dice_filter.GetFalsePositiveError()

    hd_filter = sitk.HausdorffDistanceImageFilter()
    hd_filter.Execute(gt, pred)
    right_sart_hd_lower = hd_filter.GetHausdorffDistance()

    bce = binary_cross_entropy(gt_arr, pred_arr)
    biou = boundary_iou_3d(BOUNDARY_DISTANCE, gt_arr, pred_arr)

    results_r_sart.append({
        "image": gt_name,
        "pred_label": file,
        "R_sartorius_lower_dice:": right_sart_dice_lower,
        "R_sartorius_lower_Hausdorff:": right_sart_hd_lower,
        "R_sartorius_jaccard": right_JaccardCoeffi,
        "R_sartorius_volume_similarity": right_VolumeSimilar,
        "R_sartorius_falseNegative": right_FalseNegative,
        "R_sartorius_falsePostivie": right_FalsePositive,
        "R_sartorius_binary_cross_entropy": bce,
        "R_sartorius_boundary_iou_3d": biou,
    })

df_r_sart = pd.DataFrame(results_r_sart)
df_r_sart.to_csv('../MuscleMap_results_WB/df_r_sart_NEW.csv')
df_r_sart

HV001_1_FATFRACTION_stack1_dseg.nii.gz
HV001_1/SegmentationMasks/combined_gt_stack1.mha
HV001_1_FATFRACTION_stack2_dseg.nii.gz
HV001_1/SegmentationMasks/combined_gt_stack2.mha
HV001_2_FATFRACTION_stack1_dseg.nii.gz
HV001_2/SegmentationMasks/combined_gt_stack1.mha
HV001_2_FATFRACTION_stack2_dseg.nii.gz
HV001_2/SegmentationMasks/combined_gt_stack2.mha
HV001_3_FATFRACTION_stack1_dseg.nii.gz
HV001_3/SegmentationMasks/combined_gt_stack1.mha
HV001_3_FATFRACTION_stack2_dseg.nii.gz
HV001_3/SegmentationMasks/combined_gt_stack2.mha
HV002_1_FATFRACTION_stack1_dseg.nii.gz
HV002_1/SegmentationMasks/combined_gt_stack1.mha
HV002_1_FATFRACTION_stack2_dseg.nii.gz
HV002_1/SegmentationMasks/combined_gt_stack2.mha
HV002_2_FATFRACTION_stack1_dseg.nii.gz
HV002_2/SegmentationMasks/combined_gt_stack1.mha
HV002_2_FATFRACTION_stack2_dseg.nii.gz
HV002_2/SegmentationMasks/combined_gt_stack2.mha
HV002_3_FATFRACTION_stack1_dseg.nii.gz
HV002_3/SegmentationMasks/combined_gt_stack1.mha
HV002_3_FATFRACTION_stack2_dseg.nii.gz
HV002_3/SegmentationMasks/combined_gt_stack2.mha
HV003_1_FATFRACTION_stack1_dseg.nii.gz
HV003_1/SegmentationMasks/combined_gt_stack1.mha
HV003_1_FATFRACTION_stack2_dseg.nii.gz
HV003_1/SegmentationMasks/combined_gt_stack2.mha
HV003_2_FATFRACTION_stack1_dseg.nii.gz
HV003_2/SegmentationMasks/combined_gt_stack1.mha
HV003_2_FATFRACTION_stack2_dseg.nii.gz
HV003_2/SegmentationMasks/combined_gt_stack2.mha
HV003_3_FATFRACTION_stack1_dseg.nii.gz
HV003_3/SegmentationMasks/combined_gt_stack1.mha
HV003_3_FATFRACTION_stack2_dseg.nii.gz
HV003_3/SegmentationMasks/combined_gt_stack2.mha
HV004_1_FATFRACTION_stack1_dseg.nii.gz
HV004_1/SegmentationMasks/combined_gt_stack1.mha
HV004_1_FATFRACTION_stack2_dseg.nii.gz
HV004_1/SegmentationMasks/combined_gt_stack2.mha
HV005_1_FATFRACTION_stack1_dseg.nii.gz
HV005_1/SegmentationMasks/combined_gt_stack1.mha
HV005_1_FATFRACTION_stack2_dseg.nii.gz
HV005_1/SegmentationMasks/combined_gt_stack2.mha
HV006_1_FATFRACTION_stack1_dseg.nii.gz
HV006_1/SegmentationMasks/combined_gt_stack1.mha
HV006_1_FATFRACTION_stack2_dseg.nii.gz
HV006_1/SegmentationMasks/combined_gt_stack2.mha
HV007_1_FATFRACTION_stack1_dseg.nii.gz
HV007_1/SegmentationMasks/combined_gt_stack1.mha
HV007_1_FATFRACTION_stack2_dseg.nii.gz
HV007_1/SegmentationMasks/combined_gt_stack2.mha
HV008_1_FATFRACTION_stack1_dseg.nii.gz
HV008_1/SegmentationMasks/combined_gt_stack1.mha
HV008_1_FATFRACTION_stack2_dseg.nii.gz
HV008_1/SegmentationMasks/combined_gt_stack2.mha
HV009_1_FATFRACTION_stack1_dseg.nii.gz
HV009_1/SegmentationMasks/combined_gt_stack1.mha
HV009_1_FATFRACTION_stack2_dseg.nii.gz
HV009_1/SegmentationMasks/combined_gt_stack2.mha
HV010_1_FATFRACTION_stack1_dseg.nii.gz
HV010_1/SegmentationMasks/combined_gt_stack1.mha
HV010_1_FATFRACTION_stack2_dseg.nii.gz
HV010_1/SegmentationMasks/combined_gt_stack2.mha
HV011_1_FATFRACTION_stack1_dseg.nii.gz
HV011_1/SegmentationMasks/combined_gt_stack1.mha
HV011_1_FATFRACTION_stack2_dseg.nii.gz
HV011_1/SegmentationMasks/combined_gt_stack2.mha
HV012_1_FATFRACTION_stack1_dseg.nii.gz
HV012_1/SegmentationMasks/combined_gt_stack1.mha
HV012_1_FATFRACTION_stack2_dseg.nii.gz
HV012_1/SegmentationMasks/combined_gt_stack2.mha
HV013_1_FATFRACTION_stack1_dseg.nii.gz
HV013_1/SegmentationMasks/combined_gt_stack1.mha
HV013_1_FATFRACTION_stack2_dseg.nii.gz
HV013_1/SegmentationMasks/combined_gt_stack2.mha
HV014_1_FATFRACTION_stack1_dseg.nii.gz
HV014_1/SegmentationMasks/combined_gt_stack1.mha
HV014_1_FATFRACTION_stack2_dseg.nii.gz
HV014_1/SegmentationMasks/combined_gt_stack2.mha
HV015_1_FATFRACTION_stack1_dseg.nii.gz
HV015_1/SegmentationMasks/combined_gt_stack1.mha
HV015_1_FATFRACTION_stack2_dseg.nii.gz
HV015_1/SegmentationMasks/combined_gt_stack2.mha
P001_1_FATFRACTION_stack1_dseg.nii.gz
P001_1/SegmentationMasks/combined_gt_stack1.mha
P001_1_FATFRACTION_stack2_dseg.nii.gz
P001_1/SegmentationMasks/combined_gt_stack2.mha
P001_1_FATFRACTION_stack3_dseg.nii.gz
P001_1/SegmentationMasks/combined_gt_stack3.mha
P002_1_FATFRACTION_stack1_dseg.nii.gz
P002_1/SegmentationMasks/combined_gt_stack1.mha
P002_1_FATFRACTION_stack2_dseg.nii.gz
P002_1/SegmentationMasks/combined_gt_stack2.mha
P002_1_FATFRACTION_stack3_dseg.nii.gz
P002_1/SegmentationMasks/combined_gt_stack3.mha
P003_1_FATFRACTION_stack1_dseg.nii.gz
P003_1/SegmentationMasks/combined_gt_stack1.mha
P003_1_FATFRACTION_stack2_dseg.nii.gz
P003_1/SegmentationMasks/combined_gt_stack2.mha
P003_1_FATFRACTION_stack3_dseg.nii.gz
P003_1/SegmentationMasks/combined_gt_stack3.mha
P004_1_FATFRACTION_stack1_dseg.nii.gz
P004_1/SegmentationMasks/combined_gt_stack1.mha
P004_1_FATFRACTION_stack2_dseg.nii.gz
P004_1/SegmentationMasks/combined_gt_stack2.mha
P004_1_FATFRACTION_stack3_dseg.nii.gz
P004_1/SegmentationMasks/combined_gt_stack3.mha

,image,pred_label,R_sartorius_lower_dice:,R_sartorius_lower_Hausdorff:,R_sartorius_jaccard,R_sartorius_volume_similarity,R_sartorius_falseNegative,R_sartorius_falsePostivie,R_sartorius_binary_cross_entropy,R_sartorius_boundary_iou_3d
0,HV001_1/SegmentationMasks/combined_gt_stack1.mha,HV001_1_FATFRACTION_stack1_dseg.nii.gz,0.756179,40.000000,0.607949,-0.257952,0.330208,1.154514e-04,0.007893,0.442209
1,HV001_1/SegmentationMasks/combined_gt_stack2.mha,HV001_1_FATFRACTION_stack2_dseg.nii.gz,0.798659,20.049938,0.664807,-0.237944,0.286256,8.388670e-05,0.006603,0.561325
2,HV001_2/SegmentationMasks/combined_gt_stack1.mha,HV001_2_FATFRACTION_stack1_dseg.nii.gz,0.796968,44.000000,0.662466,-0.190659,0.272395,1.146023e-04,0.006956,0.515923
3,HV001_2/SegmentationMasks/combined_gt_stack2.mha,HV001_2_FATFRACTION_stack2_dseg.nii.gz,0.880188,20.000000,0.786015,-0.042271,0.138030,1.079993e-04,0.004223,0.691655
4,HV001_3/SegmentationMasks/combined_gt_stack1.mha,HV001_3_FATFRACTION_stack1_dseg.nii.gz,0.853190,36.000000,0.743968,-0.090293,0.183665,1.146720e-04,0.005332,0.601977
5,HV001_3/SegmentationMasks/combined_gt_stack2.mha,HV001_3_FATFRACTION_stack2_dseg.nii.gz,0.884641,20.024984,0.793144,-0.005500,0.117785,1.267127e-04,0.004180,0.689993
6,HV002_1/SegmentationMasks/combined_gt_stack1.mha,HV002_1_FATFRACTION_stack1_dseg.nii.gz,0.852560,14.000000,0.743011,0.097003,0.103982,2.625225e-04,0.006360,0.604943
7,HV002_1/SegmentationMasks/combined_gt_stack2.mha,HV002_1_FATFRACTION_stack2_dseg.nii.gz,0.876557,24.269322,0.780241,0.024563,0.112544,1.544119e-04,0.004522,0.630907
8,HV002_2/SegmentationMasks/combined_gt_stack1.mha,HV002_2_FATFRACTION_stack1_dseg.nii.gz,0.835869,16.401219,0.718019,-0.084465,0.198002,1.477354e-04,0.006404,0.588234
9,HV002_2/SegmentationMasks/combined_gt_stack2.mha,HV002_2_FATFRACTION_stack2_dseg.nii.gz,0.893196,20.024984,0.807004,-0.017976,0.114761,1.162597e-04,0.004087,0.671580
10,HV002_3/SegmentationMasks/combined_gt_stack1.mha,HV002_3_FATFRACTION_stack1_dseg.nii.gz,0.859762,12.369317,0.754020,-0.044652,0.159014,1.456546e-04,0.005577,0.616056
11,HV002_3/SegmentationMasks/combined_gt_stack2.mha,HV002_3_FATFRACTION_stack2_dseg.nii.gz,0.888236,16.155494,0.798943,-0.056194,0.136039,9.228467e-05,0.003970,0.665915
12,HV003_1/SegmentationMasks/combined_gt_stack1.mha,HV003_1_FATFRACTION_stack1_dseg.nii.gz,0.865683,36.345564,0.763175,-0.009392,0.138363,1.586456e-04,0.005293,0.608412
13,HV003_1/SegmentationMasks/combined_gt_stack2.mha,HV003_1_FATFRACTION_stack2_dseg.nii.gz,0.900111,20.000000,0.818365,-0.042149,0.118467,9.248706e-05,0.003774,0.686784
14,HV003_2/SegmentationMasks/combined_gt_stack1.mha,HV003_2_FATFRACTION_stack1_dseg.nii.gz,0.859566,28.231188,0.753718,-0.116488,0.187743,9.735227e-05,0.005356,0.585879
15,HV003_2/SegmentationMasks/combined_gt_stack2.mha,HV003_2_FATFRACTION_stack2_dseg.nii.gz,0.901110,20.000000,0.820019,-0.046418,0.119329,8.904939e-05,0.003747,0.687379
16,HV003_3/SegmentationMasks/combined_gt_stack1.mha,HV003_3_FATFRACTION_stack1_dseg.nii.gz,0.834028,32.264532,0.715307,-0.220254,0.248709,6.214879e-05,0.005947,0.530536
17,HV003_3/SegmentationMasks/combined_gt_stack2.mha,HV003_3_FATFRACTION_stack2_dseg.nii.gz,0.879453,20.000000,0.784842,-0.150728,0.182182,5.059067e-05,0.004346,0.645664
18,HV004_1/SegmentationMasks/combined_gt_stack1.mha,HV004_1_FATFRACTION_stack1_dseg.nii.gz,0.825795,20.396078,0.703281,-0.154293,0.233349,9.924741e-05,0.005736,0.570541
19,HV004_1/SegmentationMasks/combined_gt_stack2.mha,HV004_1_FATFRACTION_stack2_dseg.nii.gz,0.885899,16.000000,0.795169,-0.047078,0.134475,8.908096e-05,0.003614,0.679727
20,HV005_1/SegmentationMasks/combined_gt_stack1.mha,HV005_1_FATFRACTION_stack1_dseg.nii.gz,0.788150,21.771541,0.650369,-0.169053,0.273278,1.097678e-04,0.005882,0.550015
21,HV005_1/SegmentationMasks/combined_gt_stack2.mha,HV005_1_FATFRACTION_stack2_dseg.nii.gz,0.849681,24.000000,0.738648,-0.107680,0.193728,8.544073e-05,0.004287,0.617435
22,HV006_1/SegmentationMasks/combined_gt_stack1.mha,HV006_1_FATFRACTION_stack1_dseg.nii.gz,0.855524,36.221541,0.747524,-0.128950,0.196295,7.485399e-05,0.004353,0.601088
23,HV006_1/SegmentationMasks/combined_gt_stack2.mha,HV006_1_FATFRACTION_stack2_dseg.nii.gz,0.893807,8.306624,0.808003,-0.061974,0.133056,7.675847e-05,0.003490,0.693184
24,HV007_1/SegmentationMasks/combined_gt_stack1.mha,HV007_1_FATFRACTION_stack1_dseg.nii.gz,0.805580,40.311289,0.674453,-0.188118,0.263678,8.009588e-05,0.004998,0.559338
25,HV007_1/SegmentationMasks/combined_gt_stack2.mha,HV007_1_FATFRACTION_stack2_dseg.nii.gz,0.816939,16.062378,0.690530,-0.219576,0.263878,5.921711e-05,0.004765,0.555104
26,HV008_1/SegmentationMasks/combined_gt_stack1.mha,HV008_1_FATFRACTION_stack1_dseg.nii.gz,0.841483,16.522712,0.726345,-0.111441,0.202930,9.609870e-05,0.004772,0.614675
27,HV008_1/SegmentationMasks/combined_gt_stack2.mha,HV008_1_FATFRACTION_stack2_dseg.nii.gz,0.880698,8.062258,0.786828,-0.088933,0.156797,6.255457e-05,0.003212,0.672956
28,HV009_1/SegmentationMasks/combined_gt_stack1.mha,HV009_1_FATFRACTION_stack1_dseg.nii.gz,0.845511,32.893768,0.732368,-0.063342,0.180445,1.408678e-04,0.005705,0.589754
29,HV009_1/SegmentationMasks/combined_gt_stack2.mha,HV009_1_FATFRACTION_stack2_dseg.nii.gz,0.878385,9.165151,0.783143,-0.048561,0.142437,1.127219e-04,0.004535,0.657754
30,HV010_1/SegmentationMasks/combined_gt_stack1.mha,HV010_1_FATFRACTION_stack1_dseg.nii.gz,0.775595,36.013886,0.633446,-0.254223,0.311874,3.848005e-05,0.002860,0.563185
31,HV010_1/SegmentationMasks/combined_gt_stack2.mha,HV010_1_FATFRACTION_stack2_dseg.nii.gz,0.830711,8.000000,0.710441,-0.199414,0.244607,3.440842e-05,0.002697,0.691049
32,HV011_1/SegmentationMasks/combined_gt_stack1.mha,HV011_1_FATFRACTION_stack1_dseg.nii.gz,0.765967,40.012498,0.620702,-0.264906,0.323622,3.997971e-05,0.002968,0.545892
33,HV011_1/SegmentationMasks/combined_gt_stack2.mha,HV011_1_FATFRACTION_stack2_dseg.nii.gz,0.833767,8.000000,0.714923,-0.176300,0.233776,3.902239e-05,0.002677,0.697250
34,HV012_1/SegmentationMasks/combined_gt_stack1.mha,HV012_1_FATFRACTION_stack1_dseg.nii.gz,0.751665,11.180340,0.602133,-0.462672,0.389554,1.191504e-05,0.005606,0.501194
35,HV012_1/SegmentationMasks/combined_gt_stack2.mha,HV012_1_FATFRACTION_stack2_dseg.nii.gz,0.607805,8.485281,0.436580,-0.761405,0.559786,1.142439e-05,0.012551,0.343059
36,HV013_1/SegmentationMasks/combined_gt_stack1.mha,HV013_1_FATFRACTION_stack1_dseg.nii.gz,0.732107,24.083189,0.577420,-0.491456,0.412306,2.016171e-05,0.007846,0.466300
37,HV013_1/SegmentationMasks/combined_gt_stack2.mha,HV013_1_FATFRACTION_stack2_dseg.nii.gz,0.742339,24.535688,0.590253,-0.493326,0.404539,1.162243e-05,0.008766,0.484048
38,HV014_1/SegmentationMasks/combined_gt_stack1.mha,HV014_1_FATFRACTION_stack1_dseg.nii.gz,0.539231,24.413111,0.369142,-0.911655,0.629605,4.072340e-06,0.012226,0.337651
39,HV014_1/SegmentationMasks/combined_gt_stack2.mha,HV014_1_FATFRACTION_stack2_dseg.nii.gz,0.000000,85.005882,0.000000,-1.436066,1.000000,1.665379e-04,0.019020,0.000000
40,HV015_1/SegmentationMasks/combined_gt_stack1.mha,HV015_1_FATFRACTION_stack1_dseg.nii.gz,0.702382,13.928388,0.541286,-0.538272,0.446567,3.338292e-05,0.011228,0.414592
41,HV015_1/SegmentationMasks/combined_gt_stack2.mha,HV015_1_FATFRACTION_stack2_dseg.nii.gz,0.738219,12.206556,0.585061,-0.406975,0.386600,6.974313e-05,0.010082,0.500022
42,P001_1/SegmentationMasks/combined_gt_stack1.mha,P001_1_FATFRACTION_stack1_dseg.nii.gz,0.857014,4.358899,0.749803,-0.200300,0.221003,9.087424e-05,0.009756,0.643050
43,P001_1/SegmentationMasks/combined_gt_stack2.mha,P001_1_FATFRACTION_stack2_dseg.nii.gz,0.890653,5.744563,0.802862,-0.087433,0.146652,1.496371e-04,0.008018,0.668631
44,P001_1/SegmentationMasks/combined_gt_stack3.mha,P001_1_FATFRACTION_stack3_dseg.nii.gz,0.789062,8.944272,0.651612,-0.191490,0.279885,1.867427e-04,0.011004,0.451876
45,P002_1/SegmentationMasks/combined_gt_stack1.mha,P002_1_FATFRACTION_stack1_dseg.nii.gz,0.816122,4.358899,0.689364,-0.348497,0.304983,9.930224e-06,0.006106,0.534324
46,P002_1/SegmentationMasks/combined_gt_stack2.mha,P002_1_FATFRACTION_stack2_dseg.nii.gz,0.771764,4.472136,0.628351,-0.438750,0.367082,9.421786e-06,0.007813,0.519882
47,P002_1/SegmentationMasks/combined_gt_stack3.mha,P002_1_FATFRACTION_stack3_dseg.nii.gz,0.580210,13.453624,0.408659,-0.838407,0.591172,5.092527e-07,0.011730,0.265331
48,P003_1/SegmentationMasks/combined_gt_stack1.mha,P003_1_FATFRACTION_stack1_dseg.nii.gz,0.759643,4.242641,0.612439,-0.462986,0.383153,1.031444e-05,0.009004,0.539277
49,P003_1/SegmentationMasks/combined_gt_stack2.mha,P003_1_FATFRACTION_stack2_dseg.nii.gz,0.781868,4.898979,0.641859,-0.336390,0.330704,7.247476e-05,0.010188,0.526208
50,P003_1/SegmentationMasks/combined_gt_stack3.mha,P003_1_FATFRACTION_stack3_dseg.nii.gz,0.754765,5.656854,0.606123,-0.488098,0.393300,1.655908e-06,0.011022,0.370109
51,P004_1/SegmentationMasks/combined_gt_stack1.mha,P004_1_FATFRACTION_stack1_dseg.nii.gz,0.800377,8.485281,0.667190,-0.341012,0.316213,4.330850e-05,0.009555,0.555111
52,P004_1/SegmentationMasks/combined_gt_stack2.mha,P004_1_FATFRACTION_stack2_dseg.nii.gz,0.807495,4.472136,0.677142,-0.337714,0.309158,2.852323e-05,0.007475,0.583056
53,P004_1/SegmentationMasks/combined_gt_stack3.mha,P004_1_FATFRACTION_stack3_dseg.nii.gz,0.649907,21.213203,0.481380,-0.631092,0.505979,2.851400e-05,0.009305,0.357881

## Left sartorius

In [7]:
results_l_sart = []
for file in os.listdir(os.path.join("..", "MuscleMap_segs")):
    print(file)
    if file[0] == 'H':
        gt_name = file[:7] + "/SegmentationMasks/combined_gt_stack" + file[-13] + ".mha"
    else:
        gt_name = file[:6] + "/SegmentationMasks/combined_gt_stack" + file[-13] + ".mha"
    print(gt_name)

    segment_image = sitk.ReadImage(os.path.join("..", "MuscleMap_segs", file))
    gt_image = sitk.ReadImage(gt_name)
    segment_image.CopyInformation(gt_image)

    gt = sitk.Cast(gt_image == 4, sitk.sitkUInt8)
    pred = sitk.Cast(segment_image == 7141, sitk.sitkUInt8)

    gt_arr = sitk.GetArrayFromImage(gt).astype(float)
    pred_arr = sitk.GetArrayFromImage(pred).astype(float)

    dice_filter = sitk.LabelOverlapMeasuresImageFilter()
    dice_filter.Execute(gt, pred)
    left_sart_dice_lower = dice_filter.GetDiceCoefficient()
    left_JaccardCoeffi = dice_filter.GetJaccardCoefficient()
    left_VolumeSimilar = dice_filter.GetVolumeSimilarity()
    left_FalseNegative = dice_filter.GetFalseNegativeError()
    left_FalsePositive = dice_filter.GetFalsePositiveError()

    hd_filter = sitk.HausdorffDistanceImageFilter()
    hd_filter.Execute(gt, pred)
    left_sart_hd_lower = hd_filter.GetHausdorffDistance()

    bce = binary_cross_entropy(gt_arr, pred_arr)
    biou = boundary_iou_3d(BOUNDARY_DISTANCE, gt_arr, pred_arr)

    results_l_sart.append({
        "image": gt_name,
        "pred_label": file,
        "L_sartorius_lower_dice:": left_sart_dice_lower,
        "L_sartorius_lower_Hausdorff:": left_sart_hd_lower,
        "L_sartorius_jaccard": left_JaccardCoeffi,
        "L_sartorius_volume_similarity": left_VolumeSimilar,
        "L_sartorius_falseNegative": left_FalseNegative,
        "L_sartorius_falsePostivie": left_FalsePositive,
        "L_sartorius_binary_cross_entropy": bce,
        "L_sartorius_boundary_iou_3d": biou,
    })

df_l_sart = pd.DataFrame(results_l_sart)
df_l_sart.to_csv('../MuscleMap_results_WB/df_l_sart_NEW.csv')
df_l_sart

HV001_1_FATFRACTION_stack1_dseg.nii.gz
HV001_1/SegmentationMasks/combined_gt_stack1.mha
HV001_1_FATFRACTION_stack2_dseg.nii.gz
HV001_1/SegmentationMasks/combined_gt_stack2.mha
HV001_2_FATFRACTION_stack1_dseg.nii.gz
HV001_2/SegmentationMasks/combined_gt_stack1.mha
HV001_2_FATFRACTION_stack2_dseg.nii.gz
HV001_2/SegmentationMasks/combined_gt_stack2.mha
HV001_3_FATFRACTION_stack1_dseg.nii.gz
HV001_3/SegmentationMasks/combined_gt_stack1.mha
HV001_3_FATFRACTION_stack2_dseg.nii.gz
HV001_3/SegmentationMasks/combined_gt_stack2.mha
HV002_1_FATFRACTION_stack1_dseg.nii.gz
HV002_1/SegmentationMasks/combined_gt_stack1.mha
HV002_1_FATFRACTION_stack2_dseg.nii.gz
HV002_1/SegmentationMasks/combined_gt_stack2.mha
HV002_2_FATFRACTION_stack1_dseg.nii.gz
HV002_2/SegmentationMasks/combined_gt_stack1.mha
HV002_2_FATFRACTION_stack2_dseg.nii.gz
HV002_2/SegmentationMasks/combined_gt_stack2.mha
HV002_3_FATFRACTION_stack1_dseg.nii.gz
HV002_3/SegmentationMasks/combined_gt_stack1.mha
HV002_3_FATFRACTION_stack2_dseg.nii.gz
HV002_3/SegmentationMasks/combined_gt_stack2.mha
HV003_1_FATFRACTION_stack1_dseg.nii.gz
HV003_1/SegmentationMasks/combined_gt_stack1.mha
HV003_1_FATFRACTION_stack2_dseg.nii.gz
HV003_1/SegmentationMasks/combined_gt_stack2.mha
HV003_2_FATFRACTION_stack1_dseg.nii.gz
HV003_2/SegmentationMasks/combined_gt_stack1.mha
HV003_2_FATFRACTION_stack2_dseg.nii.gz
HV003_2/SegmentationMasks/combined_gt_stack2.mha
HV003_3_FATFRACTION_stack1_dseg.nii.gz
HV003_3/SegmentationMasks/combined_gt_stack1.mha
HV003_3_FATFRACTION_stack2_dseg.nii.gz
HV003_3/SegmentationMasks/combined_gt_stack2.mha
HV004_1_FATFRACTION_stack1_dseg.nii.gz
HV004_1/SegmentationMasks/combined_gt_stack1.mha
HV004_1_FATFRACTION_stack2_dseg.nii.gz
HV004_1/SegmentationMasks/combined_gt_stack2.mha
HV005_1_FATFRACTION_stack1_dseg.nii.gz
HV005_1/SegmentationMasks/combined_gt_stack1.mha
HV005_1_FATFRACTION_stack2_dseg.nii.gz
HV005_1/SegmentationMasks/combined_gt_stack2.mha
HV006_1_FATFRACTION_stack1_dseg.nii.gz
HV006_1/SegmentationMasks/combined_gt_stack1.mha
HV006_1_FATFRACTION_stack2_dseg.nii.gz
HV006_1/SegmentationMasks/combined_gt_stack2.mha
HV007_1_FATFRACTION_stack1_dseg.nii.gz
HV007_1/SegmentationMasks/combined_gt_stack1.mha
HV007_1_FATFRACTION_stack2_dseg.nii.gz
HV007_1/SegmentationMasks/combined_gt_stack2.mha
HV008_1_FATFRACTION_stack1_dseg.nii.gz
HV008_1/SegmentationMasks/combined_gt_stack1.mha
HV008_1_FATFRACTION_stack2_dseg.nii.gz
HV008_1/SegmentationMasks/combined_gt_stack2.mha
HV009_1_FATFRACTION_stack1_dseg.nii.gz
HV009_1/SegmentationMasks/combined_gt_stack1.mha
HV009_1_FATFRACTION_stack2_dseg.nii.gz
HV009_1/SegmentationMasks/combined_gt_stack2.mha
HV010_1_FATFRACTION_stack1_dseg.nii.gz
HV010_1/SegmentationMasks/combined_gt_stack1.mha
HV010_1_FATFRACTION_stack2_dseg.nii.gz
HV010_1/SegmentationMasks/combined_gt_stack2.mha
HV011_1_FATFRACTION_stack1_dseg.nii.gz
HV011_1/SegmentationMasks/combined_gt_stack1.mha
HV011_1_FATFRACTION_stack2_dseg.nii.gz
HV011_1/SegmentationMasks/combined_gt_stack2.mha
HV012_1_FATFRACTION_stack1_dseg.nii.gz
HV012_1/SegmentationMasks/combined_gt_stack1.mha
HV012_1_FATFRACTION_stack2_dseg.nii.gz
HV012_1/SegmentationMasks/combined_gt_stack2.mha
HV013_1_FATFRACTION_stack1_dseg.nii.gz
HV013_1/SegmentationMasks/combined_gt_stack1.mha
HV013_1_FATFRACTION_stack2_dseg.nii.gz
HV013_1/SegmentationMasks/combined_gt_stack2.mha
HV014_1_FATFRACTION_stack1_dseg.nii.gz
HV014_1/SegmentationMasks/combined_gt_stack1.mha
HV014_1_FATFRACTION_stack2_dseg.nii.gz
HV014_1/SegmentationMasks/combined_gt_stack2.mha
HV015_1_FATFRACTION_stack1_dseg.nii.gz
HV015_1/SegmentationMasks/combined_gt_stack1.mha
HV015_1_FATFRACTION_stack2_dseg.nii.gz
HV015_1/SegmentationMasks/combined_gt_stack2.mha
P001_1_FATFRACTION_stack1_dseg.nii.gz
P001_1/SegmentationMasks/combined_gt_stack1.mha
P001_1_FATFRACTION_stack2_dseg.nii.gz
P001_1/SegmentationMasks/combined_gt_stack2.mha
P001_1_FATFRACTION_stack3_dseg.nii.gz
P001_1/SegmentationMasks/combined_gt_stack3.mha
P002_1_FATFRACTION_stack1_dseg.nii.gz
P002_1/SegmentationMasks/combined_gt_stack1.mha
P002_1_FATFRACTION_stack2_dseg.nii.gz
P002_1/SegmentationMasks/combined_gt_stack2.mha
P002_1_FATFRACTION_stack3_dseg.nii.gz
P002_1/SegmentationMasks/combined_gt_stack3.mha
P003_1_FATFRACTION_stack1_dseg.nii.gz
P003_1/SegmentationMasks/combined_gt_stack1.mha
P003_1_FATFRACTION_stack2_dseg.nii.gz
P003_1/SegmentationMasks/combined_gt_stack2.mha
P003_1_FATFRACTION_stack3_dseg.nii.gz
P003_1/SegmentationMasks/combined_gt_stack3.mha
P004_1_FATFRACTION_stack1_dseg.nii.gz
P004_1/SegmentationMasks/combined_gt_stack1.mha
P004_1_FATFRACTION_stack2_dseg.nii.gz
P004_1/SegmentationMasks/combined_gt_stack2.mha
P004_1_FATFRACTION_stack3_dseg.nii.gz
P004_1/SegmentationMasks/combined_gt_stack3.mha

,image,pred_label,L_sartorius_lower_dice:,L_sartorius_lower_Hausdorff:,L_sartorius_jaccard,L_sartorius_volume_similarity,L_sartorius_falseNegative,L_sartorius_falsePostivie,L_sartorius_binary_cross_entropy,L_sartorius_boundary_iou_3d
0,HV001_1/SegmentationMasks/combined_gt_stack1.mha,HV001_1_FATFRACTION_stack1_dseg.nii.gz,0.872514,20.000000,0.773858,-0.106311,0.171524,6.697327e-05,0.003699,0.635402
1,HV001_1/SegmentationMasks/combined_gt_stack2.mha,HV001_1_FATFRACTION_stack2_dseg.nii.gz,0.862302,44.022721,0.757935,-0.139220,0.193817,7.362312e-05,0.004794,0.666312
2,HV001_2/SegmentationMasks/combined_gt_stack1.mha,HV001_2_FATFRACTION_stack1_dseg.nii.gz,0.858329,40.000000,0.751819,-0.022031,0.151023,1.282232e-04,0.004478,0.611927
3,HV001_2/SegmentationMasks/combined_gt_stack2.mha,HV001_2_FATFRACTION_stack2_dseg.nii.gz,0.866801,36.000000,0.764916,0.040740,0.115175,1.734649e-04,0.004845,0.661677
4,HV001_3/SegmentationMasks/combined_gt_stack1.mha,HV001_3_FATFRACTION_stack1_dseg.nii.gz,0.874369,28.000000,0.776781,0.005699,0.123132,1.314666e-04,0.004140,0.643029
5,HV001_3/SegmentationMasks/combined_gt_stack2.mha,HV001_3_FATFRACTION_stack2_dseg.nii.gz,0.872920,32.015621,0.774496,-0.022475,0.136781,1.263165e-04,0.004462,0.671402
6,HV002_1/SegmentationMasks/combined_gt_stack1.mha,HV002_1_FATFRACTION_stack1_dseg.nii.gz,0.846887,14.142136,0.734436,0.174330,0.072244,3.269826e-04,0.006709,0.593340
7,HV002_1/SegmentationMasks/combined_gt_stack2.mha,HV002_1_FATFRACTION_stack2_dseg.nii.gz,0.869859,28.071338,0.769690,-0.062181,0.156370,1.153267e-04,0.004879,0.623708
8,HV002_2/SegmentationMasks/combined_gt_stack1.mha,HV002_2_FATFRACTION_stack1_dseg.nii.gz,0.866017,13.892444,0.763694,0.141338,0.068129,2.681355e-04,0.005652,0.628343
9,HV002_2/SegmentationMasks/combined_gt_stack2.mha,HV002_2_FATFRACTION_stack2_dseg.nii.gz,0.872744,24.269322,0.774220,-0.028132,0.139361,1.424992e-04,0.005158,0.621442
10,HV002_3/SegmentationMasks/combined_gt_stack1.mha,HV002_3_FATFRACTION_stack1_dseg.nii.gz,0.868631,15.264338,0.767770,0.158533,0.056588,2.872478e-04,0.005768,0.631162
11,HV002_3/SegmentationMasks/combined_gt_stack2.mha,HV002_3_FATFRACTION_stack2_dseg.nii.gz,0.869371,28.017851,0.768926,-0.011264,0.135498,1.509877e-04,0.005080,0.611451
12,HV003_1/SegmentationMasks/combined_gt_stack1.mha,HV003_1_FATFRACTION_stack1_dseg.nii.gz,0.873400,20.000000,0.775253,0.041228,0.108217,1.722070e-04,0.004769,0.618251
13,HV003_1/SegmentationMasks/combined_gt_stack2.mha,HV003_1_FATFRACTION_stack2_dseg.nii.gz,0.900034,28.000000,0.818237,0.019774,0.090979,1.282387e-04,0.003758,0.698645
14,HV003_2/SegmentationMasks/combined_gt_stack1.mha,HV003_2_FATFRACTION_stack1_dseg.nii.gz,0.890174,16.000000,0.802085,0.036194,0.093419,1.527359e-04,0.004222,0.651774
15,HV003_2/SegmentationMasks/combined_gt_stack2.mha,HV003_2_FATFRACTION_stack2_dseg.nii.gz,0.892570,28.000000,0.805984,0.030513,0.093601,1.425786e-04,0.004020,0.678195
16,HV003_3/SegmentationMasks/combined_gt_stack1.mha,HV003_3_FATFRACTION_stack1_dseg.nii.gz,0.886477,16.000000,0.796102,0.015899,0.106419,1.391559e-04,0.004188,0.642877
17,HV003_3/SegmentationMasks/combined_gt_stack2.mha,HV003_3_FATFRACTION_stack2_dseg.nii.gz,0.893042,28.071338,0.806754,0.061717,0.078523,1.666000e-04,0.004163,0.686200
18,HV004_1/SegmentationMasks/combined_gt_stack1.mha,HV004_1_FATFRACTION_stack1_dseg.nii.gz,0.875426,20.049938,0.778452,-0.018099,0.132425,1.097021e-04,0.003810,0.671362
19,HV004_1/SegmentationMasks/combined_gt_stack2.mha,HV004_1_FATFRACTION_stack2_dseg.nii.gz,0.875950,36.027767,0.779281,0.045431,0.103690,1.507104e-04,0.004102,0.657261
20,HV005_1/SegmentationMasks/combined_gt_stack1.mha,HV005_1_FATFRACTION_stack1_dseg.nii.gz,0.862586,20.615528,0.758375,-0.004586,0.139387,1.366493e-04,0.004475,0.644664
21,HV005_1/SegmentationMasks/combined_gt_stack2.mha,HV005_1_FATFRACTION_stack2_dseg.nii.gz,0.863443,24.000000,0.759700,-0.039977,0.153478,1.208596e-04,0.004559,0.621587
22,HV006_1/SegmentationMasks/combined_gt_stack1.mha,HV006_1_FATFRACTION_stack1_dseg.nii.gz,0.877771,20.000000,0.782168,0.126584,0.062919,1.924673e-04,0.004084,0.630833
23,HV006_1/SegmentationMasks/combined_gt_stack2.mha,HV006_1_FATFRACTION_stack2_dseg.nii.gz,0.896262,5.830952,0.812025,0.046101,0.082591,1.416871e-04,0.003733,0.692412
24,HV007_1/SegmentationMasks/combined_gt_stack1.mha,HV007_1_FATFRACTION_stack1_dseg.nii.gz,0.815854,36.000000,0.688981,-0.083028,0.216665,1.048397e-04,0.004360,0.570709
25,HV007_1/SegmentationMasks/combined_gt_stack2.mha,HV007_1_FATFRACTION_stack2_dseg.nii.gz,0.815667,20.049938,0.688714,-0.172902,0.249238,7.251711e-05,0.004399,0.566312
26,HV008_1/SegmentationMasks/combined_gt_stack1.mha,HV008_1_FATFRACTION_stack1_dseg.nii.gz,0.868249,16.031220,0.767172,-0.019199,0.140007,1.149869e-04,0.003994,0.671322
27,HV008_1/SegmentationMasks/combined_gt_stack2.mha,HV008_1_FATFRACTION_stack2_dseg.nii.gz,0.882355,8.062258,0.789476,-0.031780,0.131447,8.410706e-05,0.003132,0.666533
28,HV009_1/SegmentationMasks/combined_gt_stack1.mha,HV009_1_FATFRACTION_stack1_dseg.nii.gz,0.839489,32.249031,0.723379,0.153406,0.090770,2.687375e-04,0.005856,0.556775
29,HV009_1/SegmentationMasks/combined_gt_stack2.mha,HV009_1_FATFRACTION_stack2_dseg.nii.gz,0.877898,20.024984,0.782369,0.068667,0.090889,1.777852e-04,0.004468,0.644036
30,HV010_1/SegmentationMasks/combined_gt_stack1.mha,HV010_1_FATFRACTION_stack1_dseg.nii.gz,0.794563,24.020824,0.659149,-0.150788,0.261143,5.640903e-05,0.002871,0.592348
31,HV010_1/SegmentationMasks/combined_gt_stack2.mha,HV010_1_FATFRACTION_stack2_dseg.nii.gz,0.817675,8.000000,0.691582,-0.000343,0.182465,1.042099e-04,0.003361,0.651304
32,HV011_1/SegmentationMasks/combined_gt_stack1.mha,HV011_1_FATFRACTION_stack1_dseg.nii.gz,0.799628,28.017851,0.666150,-0.036770,0.214808,8.333538e-05,0.002957,0.589338
33,HV011_1/SegmentationMasks/combined_gt_stack2.mha,HV011_1_FATFRACTION_stack2_dseg.nii.gz,0.821513,8.000000,0.697092,-0.012690,0.183666,9.787779e-05,0.003270,0.656828
34,HV012_1/SegmentationMasks/combined_gt_stack1.mha,HV012_1_FATFRACTION_stack1_dseg.nii.gz,0.714561,9.165151,0.555888,-0.464310,0.420072,3.435266e-05,0.005928,0.430491
35,HV012_1/SegmentationMasks/combined_gt_stack2.mha,HV012_1_FATFRACTION_stack2_dseg.nii.gz,0.589134,10.049876,0.417569,-0.810081,0.580700,6.557975e-06,0.014885,0.298557
36,HV013_1/SegmentationMasks/combined_gt_stack1.mha,HV013_1_FATFRACTION_stack1_dseg.nii.gz,0.707515,8.774964,0.547407,-0.553374,0.445819,1.350679e-05,0.008053,0.437241
37,HV013_1/SegmentationMasks/combined_gt_stack2.mha,HV013_1_FATFRACTION_stack2_dseg.nii.gz,0.645060,24.103942,0.476080,-0.705865,0.523214,2.086262e-06,0.011873,0.364416
38,HV014_1/SegmentationMasks/combined_gt_stack1.mha,HV014_1_FATFRACTION_stack1_dseg.nii.gz,0.659603,10.000000,0.492096,-0.674499,0.506746,2.979959e-06,0.010378,0.397926
39,HV014_1/SegmentationMasks/combined_gt_stack2.mha,HV014_1_FATFRACTION_stack2_dseg.nii.gz,0.627404,9.000000,0.457093,-0.710922,0.537129,1.499793e-05,0.010501,0.420328
40,HV015_1/SegmentationMasks/combined_gt_stack1.mha,HV015_1_FATFRACTION_stack1_dseg.nii.gz,0.714859,20.322401,0.556250,-0.520168,0.432689,2.851305e-05,0.010445,0.418744
41,HV015_1/SegmentationMasks/combined_gt_stack2.mha,HV015_1_FATFRACTION_stack2_dseg.nii.gz,0.614420,17.204651,0.443439,-0.768046,0.556062,1.888085e-06,0.015050,0.303411
42,P001_1/SegmentationMasks/combined_gt_stack1.mha,P001_1_FATFRACTION_stack1_dseg.nii.gz,0.688510,11.747340,0.524983,0.347911,0.166498,1.107966e-03,0.022875,0.440081
43,P001_1/SegmentationMasks/combined_gt_stack2.mha,P001_1_FATFRACTION_stack2_dseg.nii.gz,0.847974,13.892444,0.736071,-0.099322,0.192145,2.443700e-04,0.011670,0.556291
44,P001_1/SegmentationMasks/combined_gt_stack3.mha,P001_1_FATFRACTION_stack3_dseg.nii.gz,0.800262,10.488088,0.667030,-0.075864,0.228984,2.678698e-04,0.010641,0.500661
45,P002_1/SegmentationMasks/combined_gt_stack1.mha,P002_1_FATFRACTION_stack1_dseg.nii.gz,0.839154,3.000000,0.722881,-0.254108,0.255445,4.189297e-05,0.006419,0.556414
46,P002_1/SegmentationMasks/combined_gt_stack2.mha,P002_1_FATFRACTION_stack2_dseg.nii.gz,0.760178,5.099020,0.613134,-0.468485,0.384094,6.876900e-06,0.009514,0.487816
47,P002_1/SegmentationMasks/combined_gt_stack3.mha,P002_1_FATFRACTION_stack3_dseg.nii.gz,0.658846,11.180340,0.491253,-0.681795,0.508653,2.546518e-07,0.010908,0.322374
48,P003_1/SegmentationMasks/combined_gt_stack1.mha,P003_1_FATFRACTION_stack1_dseg.nii.gz,0.803388,3.000000,0.671385,-0.332573,0.311157,3.807549e-05,0.007946,0.585461
49,P003_1/SegmentationMasks/combined_gt_stack2.mha,P003_1_FATFRACTION_stack2_dseg.nii.gz,0.759562,5.916080,0.612333,-0.478412,0.387058,1.783385e-06,0.011197,0.493795
50,P003_1/SegmentationMasks/combined_gt_stack3.mha,P003_1_FATFRACTION_stack3_dseg.nii.gz,0.822021,5.744563,0.697824,-0.307860,0.287633,3.081739e-05,0.007341,0.545111
51,P004_1/SegmentationMasks/combined_gt_stack1.mha,P004_1_FATFRACTION_stack1_dseg.nii.gz,0.817219,3.605551,0.690930,-0.277569,0.282377,5.896335e-05,0.007885,0.583226
52,P004_1/SegmentationMasks/combined_gt_stack2.mha,P004_1_FATFRACTION_stack2_dseg.nii.gz,0.820745,4.358899,0.695987,-0.313153,0.290367,2.928970e-05,0.007452,0.581754
53,P004_1/SegmentationMasks/combined_gt_stack3.mha,P004_1_FATFRACTION_stack3_dseg.nii.gz,0.659756,17.000000,0.492266,-0.599535,0.492405,3.653675e-05,0.009889,0.359888