# MuscleMap Thigh — Extended Metrics (_LONGER)

Reads the existing 6-metric CSVs from `MuscleMap_results_thigh/`, loads each
MuscleMap thigh NIfTI prediction, computes the four missing metrics
(`binary_cross_entropy`, `boundary_iou_3d`, `inter_slice_dice_pred`,
`inter_slice_dice_gt`), and saves `*_LONGER.csv` files in the same folder.

Run this notebook from `evaluation_code/` so relative paths resolve correctly.

In [1]:
# libraries
import os
import re
import numpy as np
import pandas as pd
import SimpleITK as sitk
from dissector.evaluation import binary_cross_entropy, boundary_iou_3d, inter_slice_dice

BOUNDARY_DISTANCE = 1

GT_BASE   = os.path.join("..", "..", "myosegmenTUM")
PRED_DIR  = os.path.join("..", "..", "MuscleMap_thigh_segs")
CSV_IN    = os.path.join("..", "..", "MuscleMap_results_thigh")
CSV_OUT   = CSV_IN   # _LONGER.csv files go in the same folder

## Left Gracilis  (GT label 1 · pred label 7151)

In [3]:
existing = pd.read_csv(os.path.join(CSV_IN, "df_l_gracilis_thigh.csv"), index_col=0)

In [4]:

extra_rows = []
for _, row in existing.iterrows():
    gt_path   = os.path.join(GT_BASE, row["image"])
    pred_path = os.path.join(PRED_DIR, row["pred_label"])

    gt_image      = sitk.ReadImage(gt_path)
    segment_image = sitk.ReadImage(pred_path)
    segment_image.CopyInformation(gt_image)

    gt   = sitk.Cast(gt_image      == 1,        sitk.sitkUInt8)
    pred = sitk.Cast(segment_image == 7151,  sitk.sitkUInt8)

    gt_arr   = sitk.GetArrayFromImage(gt).astype(float)
    pred_arr = sitk.GetArrayFromImage(pred).astype(float)

    bce      = binary_cross_entropy(gt_arr, pred_arr)
    biou     = boundary_iou_3d(BOUNDARY_DISTANCE, gt_arr, pred_arr)
    isd_pred = inter_slice_dice(pred_arr)
    isd_gt   = inter_slice_dice(gt_arr)

    extra_rows.append({
        "L_gracilis_binary_cross_entropy":  bce,
        "L_gracilis_boundary_iou_3d":       biou,
        "L_gracilis_inter_slice_dice_pred": isd_pred,
        "L_gracilis_inter_slice_dice_gt":   isd_gt,
    })

extra_df = pd.DataFrame(extra_rows, index=existing.index)
longer   = pd.concat([existing, extra_df], axis=1)
longer.to_csv(os.path.join(CSV_OUT, "df_l_gracilis_thigh_LONGER.csv"))
longer

,image,pred_label,L_gracilis_lower_dice:,L_gracilis_lower_Hausdorff:,L_gracilis_jaccard,L_gracilis_volume_similarity,L_gracilis_falseNegative,L_gracilis_falsePostivie,L_gracilis_binary_cross_entropy,L_gracilis_boundary_iou_3d,L_gracilis_inter_slice_dice_pred,L_gracilis_inter_slice_dice_gt
0,HV001_1/SegmentationMasks/combined_gt_stack1.mha,HV001_1_FATFRACTION_stack1_dseg.nii.gz,0.764219,7.000000,0.618410,-1.440162,0.241125,1.079450e-04,0.007549,0.0,0.0,0.832556
1,HV001_1/SegmentationMasks/combined_gt_stack2.mha,HV001_1_FATFRACTION_stack2_dseg.nii.gz,0.818813,8.124038,0.693212,-1.440162,0.194773,1.226401e-04,0.011818,0.0,0.0,0.856624
2,HV001_2/SegmentationMasks/combined_gt_stack1.mha,HV001_2_FATFRACTION_stack1_dseg.nii.gz,0.782853,5.000000,0.643187,-1.440162,0.243911,8.916746e-05,0.007624,0.0,0.0,0.839087
3,HV001_2/SegmentationMasks/combined_gt_stack2.mha,HV001_2_FATFRACTION_stack2_dseg.nii.gz,0.812660,16.062378,0.684438,-1.440162,0.178389,1.460542e-04,0.011996,0.0,0.0,0.841345
4,HV001_3/SegmentationMasks/combined_gt_stack1.mha,HV001_3_FATFRACTION_stack1_dseg.nii.gz,0.764064,7.280110,0.618207,-1.440162,0.249423,1.106081e-04,0.008028,0.0,0.0,0.846066
5,HV001_3/SegmentationMasks/combined_gt_stack2.mha,HV001_3_FATFRACTION_stack2_dseg.nii.gz,0.810362,12.529964,0.681184,-1.440162,0.214702,1.082006e-04,0.010697,0.0,0.0,0.847258
6,HV002_1/SegmentationMasks/combined_gt_stack1.mha,HV002_1_FATFRACTION_stack1_dseg.nii.gz,0.745102,26.720778,0.593756,-1.440162,0.237490,2.104923e-04,0.012486,0.0,0.0,0.835501
7,HV002_1/SegmentationMasks/combined_gt_stack2.mha,HV002_1_FATFRACTION_stack2_dseg.nii.gz,0.380802,96.628153,0.235179,-1.440162,0.146207,5.835282e-04,0.012456,0.0,0.0,0.858373
8,HV002_2/SegmentationMasks/combined_gt_stack1.mha,HV002_2_FATFRACTION_stack1_dseg.nii.gz,0.751431,21.725561,0.601833,-1.440162,0.217098,2.141682e-04,0.012426,0.0,0.0,0.863958
9,HV002_2/SegmentationMasks/combined_gt_stack2.mha,HV002_2_FATFRACTION_stack2_dseg.nii.gz,0.711573,14.000000,0.552280,-1.440162,0.124794,3.311824e-04,0.013321,0.0,0.0,0.844463
10,HV002_3/SegmentationMasks/combined_gt_stack1.mha,HV002_3_FATFRACTION_stack1_dseg.nii.gz,0.716567,22.203603,0.558320,-1.440162,0.222583,2.757024e-04,0.013238,0.0,0.0,0.860142
11,HV002_3/SegmentationMasks/combined_gt_stack2.mha,HV002_3_FATFRACTION_stack2_dseg.nii.gz,0.694130,16.155494,0.531545,-1.440162,0.147286,3.108938e-04,0.012077,0.0,0.0,0.875203
12,HV003_1/SegmentationMasks/combined_gt_stack1.mha,HV003_1_FATFRACTION_stack1_dseg.nii.gz,0.766201,14.035669,0.621010,-1.440162,0.148169,2.862562e-04,0.015176,0.0,0.0,0.868526
13,HV003_1/SegmentationMasks/combined_gt_stack2.mha,HV003_1_FATFRACTION_stack2_dseg.nii.gz,0.840262,20.248457,0.724527,-1.440162,0.077661,2.109163e-04,0.014873,0.0,0.0,0.865937
14,HV003_2/SegmentationMasks/combined_gt_stack1.mha,HV003_2_FATFRACTION_stack1_dseg.nii.gz,0.758476,9.797959,0.610924,-1.440162,0.162104,2.845844e-04,0.014921,0.0,0.0,0.864854
15,HV003_2/SegmentationMasks/combined_gt_stack2.mha,HV003_2_FATFRACTION_stack2_dseg.nii.gz,0.845140,24.103942,0.731812,-1.440162,0.071925,2.064972e-04,0.014835,0.0,0.0,0.867160
16,HV003_3/SegmentationMasks/combined_gt_stack1.mha,HV003_3_FATFRACTION_stack1_dseg.nii.gz,0.781310,12.041595,0.641106,-1.440162,0.133047,2.688321e-04,0.014985,0.0,0.0,0.867239
17,HV003_3/SegmentationMasks/combined_gt_stack2.mha,HV003_3_FATFRACTION_stack2_dseg.nii.gz,0.857096,24.041631,0.749928,-1.440162,0.067180,2.005179e-04,0.015581,0.0,0.0,0.869828
18,HV004_1/SegmentationMasks/combined_gt_stack1.mha,HV004_1_FATFRACTION_stack1_dseg.nii.gz,0.763780,15.394804,0.617835,-1.440162,0.303753,6.073843e-05,0.006347,0.0,0.0,0.826039
19,HV004_1/SegmentationMasks/combined_gt_stack2.mha,HV004_1_FATFRACTION_stack2_dseg.nii.gz,0.830660,12.529964,0.710367,-1.440162,0.178255,6.596180e-05,0.006633,0.0,0.0,0.840609
20,HV005_1/SegmentationMasks/combined_gt_stack1.mha,HV005_1_FATFRACTION_stack1_dseg.nii.gz,0.814822,9.797959,0.687510,-1.440162,0.149010,1.695756e-04,0.012506,0.0,0.0,0.839367
21,HV005_1/SegmentationMasks/combined_gt_stack2.mha,HV005_1_FATFRACTION_stack2_dseg.nii.gz,0.821417,24.186773,0.696953,-1.440162,0.127709,1.800739e-04,0.012957,0.0,0.0,0.861638
22,HV006_1/SegmentationMasks/combined_gt_stack1.mha,HV006_1_FATFRACTION_stack1_dseg.nii.gz,0.755810,12.409674,0.607471,-1.440162,0.216723,1.706114e-04,0.010187,0.0,0.0,0.843572
23,HV006_1/SegmentationMasks/combined_gt_stack2.mha,HV006_1_FATFRACTION_stack2_dseg.nii.gz,0.821037,16.124515,0.696407,-1.440162,0.164030,1.747500e-04,0.014553,0.0,0.0,0.867214
24,HV007_1/SegmentationMasks/combined_gt_stack1.mha,HV007_1_FATFRACTION_stack1_dseg.nii.gz,0.714532,10.246951,0.555854,-1.440162,0.288333,1.668286e-04,0.009510,0.0,0.0,0.848638
25,HV007_1/SegmentationMasks/combined_gt_stack2.mha,HV007_1_FATFRACTION_stack2_dseg.nii.gz,0.812975,8.602325,0.684885,-1.440162,0.193414,1.109896e-04,0.009903,0.0,0.0,0.855068
26,HV008_1/SegmentationMasks/combined_gt_stack1.mha,HV008_1_FATFRACTION_stack1_dseg.nii.gz,0.738917,16.155494,0.585939,-1.440162,0.179963,2.589832e-04,0.012734,0.0,0.0,0.875221
27,HV008_1/SegmentationMasks/combined_gt_stack2.mha,HV008_1_FATFRACTION_stack2_dseg.nii.gz,0.811047,12.369317,0.682152,-1.440162,0.182523,1.105404e-04,0.009119,0.0,0.0,0.850926
28,HV009_1/SegmentationMasks/combined_gt_stack1.mha,HV009_1_FATFRACTION_stack1_dseg.nii.gz,0.725788,24.758837,0.569597,-1.440162,0.282205,1.465754e-04,0.008875,0.0,0.0,0.831946
29,HV009_1/SegmentationMasks/combined_gt_stack2.mha,HV009_1_FATFRACTION_stack2_dseg.nii.gz,0.827909,7.483315,0.706353,-1.440162,0.198251,8.035587e-05,0.008979,0.0,0.0,0.823906
30,HV010_1/SegmentationMasks/combined_gt_stack1.mha,HV010_1_FATFRACTION_stack1_dseg.nii.gz,0.780452,10.049876,0.639951,-1.440162,0.305211,3.087683e-05,0.004531,0.0,0.0,0.800039
31,HV010_1/SegmentationMasks/combined_gt_stack2.mha,HV010_1_FATFRACTION_stack2_dseg.nii.gz,0.835600,12.083046,0.717622,-1.440162,0.152282,1.006249e-04,0.009201,0.0,0.0,0.859094
32,HV011_1/SegmentationMasks/combined_gt_stack1.mha,HV011_1_FATFRACTION_stack1_dseg.nii.gz,0.766028,8.246211,0.620782,-1.440162,0.253570,7.293204e-05,0.005509,0.0,0.0,0.819215
33,HV011_1/SegmentationMasks/combined_gt_stack2.mha,HV011_1_FATFRACTION_stack2_dseg.nii.gz,0.817071,16.124515,0.690719,-1.440162,0.166166,1.150069e-04,0.009308,0.0,0.0,0.850483
34,HV012_1/SegmentationMasks/combined_gt_stack1.mha,HV012_1_FATFRACTION_stack1_dseg.nii.gz,0.660505,16.031220,0.493100,-1.440162,0.501877,3.771237e-06,0.003032,0.0,0.0,0.829966
35,HV012_1/SegmentationMasks/combined_gt_stack2.mha,HV012_1_FATFRACTION_stack2_dseg.nii.gz,0.681591,6.000000,0.516980,-1.440162,0.482285,2.584054e-06,0.015183,0.0,0.0,0.869856
36,HV013_1/SegmentationMasks/combined_gt_stack1.mha,HV013_1_FATFRACTION_stack1_dseg.nii.gz,0.790797,8.062258,0.653982,-1.440162,0.327181,2.432608e-05,0.009543,0.0,0.0,0.881334
37,HV013_1/SegmentationMasks/combined_gt_stack2.mha,HV013_1_FATFRACTION_stack2_dseg.nii.gz,0.739570,13.152946,0.586760,-1.440162,0.344801,1.518840e-04,0.016179,0.0,0.0,0.855896
38,HV014_1/SegmentationMasks/combined_gt_stack1.mha,HV014_1_FATFRACTION_stack1_dseg.nii.gz,0.575290,28.000000,0.403795,-1.440162,0.588814,1.608555e-05,0.006078,0.0,0.0,0.789034
39,HV014_1/SegmentationMasks/combined_gt_stack2.mha,HV014_1_FATFRACTION_stack2_dseg.nii.gz,0.600951,32.000000,0.429542,-1.440162,0.559868,2.144721e-05,0.006511,0.0,0.0,0.716200
40,HV015_1/SegmentationMasks/combined_gt_stack1.mha,HV015_1_FATFRACTION_stack1_dseg.nii.gz,0.606378,20.024984,0.435110,-1.440162,0.545688,3.236499e-05,0.005888,0.0,0.0,0.807452
41,HV015_1/SegmentationMasks/combined_gt_stack2.mha,HV015_1_FATFRACTION_stack2_dseg.nii.gz,0.580276,32.078030,0.408724,-1.440162,0.578379,4.032926e-05,0.009324,0.0,0.0,0.775692
42,P001_1/SegmentationMasks/combined_gt_stack1.mha,P001_1_FATFRACTION_stack1_dseg.nii.gz,0.772681,6.708204,0.629569,-1.440162,0.326069,1.731028e-04,0.029403,0.0,0.0,0.870581
43,P001_1/SegmentationMasks/combined_gt_stack2.mha,P001_1_FATFRACTION_stack2_dseg.nii.gz,0.412659,26.115130,0.259969,-1.440162,0.182372,1.567077e-03,0.034860,0.0,0.0,0.882776
44,P001_1/SegmentationMasks/combined_gt_stack3.mha,P001_1_FATFRACTION_stack3_dseg.nii.gz,0.511751,15.000000,0.343862,-1.440162,0.336513,2.230862e-04,0.006161,0.0,0.0,0.787012
45,P002_1/SegmentationMasks/combined_gt_stack1.mha,P002_1_FATFRACTION_stack1_dseg.nii.gz,0.504152,11.832160,0.337035,-1.440162,0.407151,3.213335e-04,0.009221,0.0,0.0,0.777238
46,P002_1/SegmentationMasks/combined_gt_stack2.mha,P002_1_FATFRACTION_stack2_dseg.nii.gz,0.405501,30.000000,0.254312,-1.440162,0.206169,1.995945e-03,0.044167,0.0,0.0,0.935504
47,P002_1/SegmentationMasks/combined_gt_stack3.mha,P002_1_FATFRACTION_stack3_dseg.nii.gz,0.623931,9.219544,0.453415,-1.440162,0.249704,3.522860e-04,0.012178,0.0,0.0,0.863691
48,P003_1/SegmentationMasks/combined_gt_stack1.mha,P003_1_FATFRACTION_stack1_dseg.nii.gz,0.674261,7.615773,0.508592,-1.440162,0.491169,6.366445e-07,0.011111,0.0,0.0,0.829895
49,P003_1/SegmentationMasks/combined_gt_stack2.mha,P003_1_FATFRACTION_stack2_dseg.nii.gz,0.749178,5.656854,0.598949,-1.440162,0.328371,1.993269e-04,0.020961,0.0,0.0,0.892112
50,P003_1/SegmentationMasks/combined_gt_stack3.mha,P003_1_FATFRACTION_stack3_dseg.nii.gz,0.534676,12.206556,0.364886,-1.440162,0.553061,1.631330e-04,0.007850,0.0,0.0,0.840690
51,P004_1/SegmentationMasks/combined_gt_stack1.mha,P004_1_FATFRACTION_stack1_dseg.nii.gz,0.755699,5.385165,0.607328,-1.440162,0.369112,6.062111e-05,0.016841,0.0,0.0,0.841129
52,P004_1/SegmentationMasks/combined_gt_stack2.mha,P004_1_FATFRACTION_stack2_dseg.nii.gz,0.844393,3.464102,0.730693,-1.440162,0.230415,6.773338e-05,0.016855,0.0,0.0,0.915832
53,P004_1/SegmentationMasks/combined_gt_stack3.mha,P004_1_FATFRACTION_stack3_dseg.nii.gz,0.135519,9.000000,0.072685,-1.440162,0.927059,3.815110e-07,0.000133,0.0,0.0,0.000000

## Right Gracilis  (GT label 5 · pred label 7152)

In [5]:
existing = pd.read_csv(os.path.join(CSV_IN, "df_r_gracilis_thigh.csv"), index_col=0)

extra_rows = []
for _, row in existing.iterrows():
    gt_path   = os.path.join(GT_BASE, row["image"])
    pred_path = os.path.join(PRED_DIR, row["pred_label"])

    gt_image      = sitk.ReadImage(gt_path)
    segment_image = sitk.ReadImage(pred_path)
    segment_image.CopyInformation(gt_image)

    gt   = sitk.Cast(gt_image      == 5,        sitk.sitkUInt8)
    pred = sitk.Cast(segment_image == 7152,  sitk.sitkUInt8)

    gt_arr   = sitk.GetArrayFromImage(gt).astype(float)
    pred_arr = sitk.GetArrayFromImage(pred).astype(float)

    bce      = binary_cross_entropy(gt_arr, pred_arr)
    biou     = boundary_iou_3d(BOUNDARY_DISTANCE, gt_arr, pred_arr)
    isd_pred = inter_slice_dice(pred_arr)
    isd_gt   = inter_slice_dice(gt_arr)

    extra_rows.append({
        "R_gracilis_binary_cross_entropy":  bce,
        "R_gracilis_boundary_iou_3d":       biou,
        "R_gracilis_inter_slice_dice_pred": isd_pred,
        "R_gracilis_inter_slice_dice_gt":   isd_gt,
    })

extra_df = pd.DataFrame(extra_rows, index=existing.index)
longer   = pd.concat([existing, extra_df], axis=1)
longer.to_csv(os.path.join(CSV_OUT, "df_r_gracilis_thigh_LONGER.csv"))
longer

,image,pred_label,R_gracilis_lower_dice:,R_gracilis_lower_Hausdorff:,R_gracilis_jaccard,R_gracilis_volume_similarity,R_gracilis_falseNegative,R_gracilis_falsePostivie,R_gracilis_binary_cross_entropy,R_gracilis_boundary_iou_3d,R_gracilis_inter_slice_dice_pred,R_gracilis_inter_slice_dice_gt
0,HV001_1/SegmentationMasks/combined_gt_stack1.mha,HV001_1_FATFRACTION_stack1_dseg.nii.gz,0.875596,7.280110,0.778720,-0.025376,0.135375,6.152724e-05,0.008760,0.0,0.0,0.839191
1,HV001_1/SegmentationMasks/combined_gt_stack2.mha,HV001_1_FATFRACTION_stack2_dseg.nii.gz,0.870277,5.656854,0.770345,-0.196001,0.207398,2.749868e-05,0.012591,0.0,0.0,0.851258
2,HV001_2/SegmentationMasks/combined_gt_stack1.mha,HV001_2_FATFRACTION_stack1_dseg.nii.gz,0.867534,8.062258,0.766058,-0.082461,0.166818,5.246222e-05,0.008881,0.0,0.0,0.841529
3,HV001_2/SegmentationMasks/combined_gt_stack2.mha,HV001_2_FATFRACTION_stack2_dseg.nii.gz,0.851596,8.246211,0.741547,-0.253466,0.244190,1.792289e-05,0.011630,0.0,0.0,0.846513
4,HV001_3/SegmentationMasks/combined_gt_stack1.mha,HV001_3_FATFRACTION_stack1_dseg.nii.gz,0.876265,8.062258,0.779779,0.009714,0.119458,7.581194e-05,0.009543,0.0,0.0,0.861016
5,HV001_3/SegmentationMasks/combined_gt_stack2.mha,HV001_3_FATFRACTION_stack2_dseg.nii.gz,0.894545,5.744563,0.809209,-0.126912,0.158832,3.613979e-05,0.012977,0.0,0.0,0.869217
6,HV002_1/SegmentationMasks/combined_gt_stack1.mha,HV002_1_FATFRACTION_stack1_dseg.nii.gz,0.859549,19.442222,0.753693,0.011141,0.135636,1.300509e-04,0.014423,0.0,0.0,0.861451
7,HV002_1/SegmentationMasks/combined_gt_stack2.mha,HV002_1_FATFRACTION_stack2_dseg.nii.gz,0.834534,16.031220,0.716051,-0.190378,0.238000,5.533614e-05,0.011473,0.0,0.0,0.851796
8,HV002_2/SegmentationMasks/combined_gt_stack1.mha,HV002_2_FATFRACTION_stack1_dseg.nii.gz,0.876086,15.811388,0.779495,-0.011539,0.128940,1.008941e-04,0.013674,0.0,0.0,0.846928
9,HV002_2/SegmentationMasks/combined_gt_stack2.mha,HV002_2_FATFRACTION_stack2_dseg.nii.gz,0.868414,16.062378,0.767431,-0.031451,0.145031,1.052776e-04,0.014402,0.0,0.0,0.857129
10,HV002_3/SegmentationMasks/combined_gt_stack1.mha,HV002_3_FATFRACTION_stack1_dseg.nii.gz,0.830807,16.155494,0.710581,-0.152660,0.228112,7.842789e-05,0.012562,0.0,0.0,0.842405
11,HV002_3/SegmentationMasks/combined_gt_stack2.mha,HV002_3_FATFRACTION_stack2_dseg.nii.gz,0.864623,16.000000,0.761529,-0.112112,0.181272,6.746635e-05,0.012929,0.0,0.0,0.855964
12,HV003_1/SegmentationMasks/combined_gt_stack1.mha,HV003_1_FATFRACTION_stack1_dseg.nii.gz,0.782853,13.601471,0.643186,0.218380,0.121190,2.618642e-04,0.014336,0.0,0.0,0.857810
13,HV003_1/SegmentationMasks/combined_gt_stack2.mha,HV003_1_FATFRACTION_stack2_dseg.nii.gz,0.860389,12.000000,0.754985,0.026307,0.128143,1.402860e-04,0.014983,0.0,0.0,0.876626
14,HV003_2/SegmentationMasks/combined_gt_stack1.mha,HV003_2_FATFRACTION_stack1_dseg.nii.gz,0.818271,12.041595,0.692435,0.215444,0.082942,2.474891e-04,0.015254,0.0,0.0,0.867773
15,HV003_2/SegmentationMasks/combined_gt_stack2.mha,HV003_2_FATFRACTION_stack2_dseg.nii.gz,0.874134,8.306624,0.776411,0.033171,0.111123,1.317917e-04,0.015146,0.0,0.0,0.877187
16,HV003_3/SegmentationMasks/combined_gt_stack1.mha,HV003_3_FATFRACTION_stack1_dseg.nii.gz,0.788166,14.491377,0.650391,0.284480,0.081135,2.907034e-04,0.015105,0.0,0.0,0.869292
17,HV003_3/SegmentationMasks/combined_gt_stack2.mha,HV003_3_FATFRACTION_stack2_dseg.nii.gz,0.874128,12.409674,0.776400,0.056655,0.100388,1.464753e-04,0.015730,0.0,0.0,0.871103
18,HV004_1/SegmentationMasks/combined_gt_stack1.mha,HV004_1_FATFRACTION_stack1_dseg.nii.gz,0.901301,7.280110,0.820334,-0.082313,0.134327,2.842742e-05,0.007631,0.0,0.0,0.845510
19,HV004_1/SegmentationMasks/combined_gt_stack2.mha,HV004_1_FATFRACTION_stack2_dseg.nii.gz,0.840924,9.433981,0.725513,-0.277532,0.261548,9.817018e-06,0.006706,0.0,0.0,0.844612
20,HV005_1/SegmentationMasks/combined_gt_stack1.mha,HV005_1_FATFRACTION_stack1_dseg.nii.gz,0.865991,7.071068,0.763654,-0.020907,0.142968,8.038542e-05,0.010370,0.0,0.0,0.850734
21,HV005_1/SegmentationMasks/combined_gt_stack2.mha,HV005_1_FATFRACTION_stack2_dseg.nii.gz,0.854665,20.024984,0.746214,-0.138840,0.200814,4.963240e-05,0.009800,0.0,0.0,0.854482
22,HV006_1/SegmentationMasks/combined_gt_stack1.mha,HV006_1_FATFRACTION_stack1_dseg.nii.gz,0.821413,8.124038,0.696947,-0.000156,0.178651,1.170325e-04,0.010560,0.0,0.0,0.848409
23,HV006_1/SegmentationMasks/combined_gt_stack2.mha,HV006_1_FATFRACTION_stack2_dseg.nii.gz,0.893193,12.165525,0.806999,-0.105027,0.151372,5.465950e-05,0.015358,0.0,0.0,0.869235
24,HV007_1/SegmentationMasks/combined_gt_stack1.mha,HV007_1_FATFRACTION_stack1_dseg.nii.gz,0.838009,15.556349,0.721184,0.126413,0.105450,1.898069e-04,0.014432,0.0,0.0,0.865917
25,HV007_1/SegmentationMasks/combined_gt_stack2.mha,HV007_1_FATFRACTION_stack2_dseg.nii.gz,0.882603,16.248077,0.789875,-0.018931,0.125673,9.461859e-05,0.013984,0.0,0.0,0.860677
26,HV008_1/SegmentationMasks/combined_gt_stack1.mha,HV008_1_FATFRACTION_stack1_dseg.nii.gz,0.881900,8.000000,0.788749,0.001100,0.117615,9.563805e-05,0.012989,0.0,0.0,0.872936
27,HV008_1/SegmentationMasks/combined_gt_stack2.mha,HV008_1_FATFRACTION_stack2_dseg.nii.gz,0.843808,8.124038,0.729816,-0.187714,0.228594,3.888051e-05,0.009104,0.0,0.0,0.828896
28,HV009_1/SegmentationMasks/combined_gt_stack1.mha,HV009_1_FATFRACTION_stack1_dseg.nii.gz,0.850644,18.466185,0.740106,-0.047532,0.169103,7.124371e-05,0.008921,0.0,0.0,0.847080
29,HV009_1/SegmentationMasks/combined_gt_stack2.mha,HV009_1_FATFRACTION_stack2_dseg.nii.gz,0.834644,16.522712,0.716214,-0.188794,0.237348,4.339637e-05,0.008921,0.0,0.0,0.823626
30,HV010_1/SegmentationMasks/combined_gt_stack1.mha,HV010_1_FATFRACTION_stack1_dseg.nii.gz,0.880636,20.639767,0.786729,-0.155797,0.183007,1.404119e-05,0.005031,0.0,0.0,0.827090
31,HV010_1/SegmentationMasks/combined_gt_stack2.mha,HV010_1_FATFRACTION_stack2_dseg.nii.gz,0.870183,16.000000,0.770198,-0.181561,0.202239,2.307216e-05,0.008656,0.0,0.0,0.835184
32,HV011_1/SegmentationMasks/combined_gt_stack1.mha,HV011_1_FATFRACTION_stack1_dseg.nii.gz,0.876831,19.519221,0.780676,-0.134131,0.178278,1.918735e-05,0.005141,0.0,0.0,0.824879
33,HV011_1/SegmentationMasks/combined_gt_stack2.mha,HV011_1_FATFRACTION_stack2_dseg.nii.gz,0.851217,12.000000,0.740973,-0.170475,0.215640,3.774999e-05,0.008753,0.0,0.0,0.796041
34,HV012_1/SegmentationMasks/combined_gt_stack1.mha,HV012_1_FATFRACTION_stack1_dseg.nii.gz,0.594395,13.000000,0.422875,-0.763166,0.569773,3.869909e-06,0.001606,0.0,0.0,0.819229
35,HV012_1/SegmentationMasks/combined_gt_stack2.mha,HV012_1_FATFRACTION_stack2_dseg.nii.gz,0.498232,28.442925,0.331763,-1.000965,0.667952,7.943863e-07,0.004968,0.0,0.0,0.764085
36,HV013_1/SegmentationMasks/combined_gt_stack1.mha,HV013_1_FATFRACTION_stack1_dseg.nii.gz,0.761641,13.601471,0.615041,-0.425572,0.371990,1.469277e-05,0.007285,0.0,0.0,0.865528
37,HV013_1/SegmentationMasks/combined_gt_stack2.mha,HV013_1_FATFRACTION_stack2_dseg.nii.gz,0.758711,20.322401,0.611228,-0.416196,0.371979,3.794917e-05,0.014574,0.0,0.0,0.826337
38,HV014_1/SegmentationMasks/combined_gt_stack1.mha,HV014_1_FATFRACTION_stack1_dseg.nii.gz,0.586661,21.748563,0.415089,-0.816551,0.583419,3.475579e-06,0.006540,0.0,0.0,0.809648
39,HV014_1/SegmentationMasks/combined_gt_stack2.mha,HV014_1_FATFRACTION_stack2_dseg.nii.gz,0.505369,16.613248,0.338123,-0.893418,0.650677,3.257168e-05,0.006056,0.0,0.0,0.420215
40,HV015_1/SegmentationMasks/combined_gt_stack1.mha,HV015_1_FATFRACTION_stack1_dseg.nii.gz,0.656532,16.000000,0.488685,-0.649362,0.504385,1.300795e-05,0.007530,0.0,0.0,0.816350
41,HV015_1/SegmentationMasks/combined_gt_stack2.mha,HV015_1_FATFRACTION_stack2_dseg.nii.gz,0.732213,28.017851,0.577552,-0.436382,0.398934,5.921298e-05,0.015023,0.0,0.0,0.816773
42,P001_1/SegmentationMasks/combined_gt_stack1.mha,P001_1_FATFRACTION_stack1_dseg.nii.gz,0.782498,10.198039,0.642708,-0.311357,0.322910,1.266930e-04,0.027822,0.0,0.0,0.851007
43,P001_1/SegmentationMasks/combined_gt_stack2.mha,P001_1_FATFRACTION_stack2_dseg.nii.gz,0.738608,7.615773,0.585549,0.203724,0.177624,6.385697e-04,0.031171,0.0,0.0,0.909397
44,P001_1/SegmentationMasks/combined_gt_stack3.mha,P001_1_FATFRACTION_stack3_dseg.nii.gz,0.396552,16.522712,0.247312,0.421108,0.497684,1.981480e-04,0.004749,0.0,0.0,0.789209
45,P002_1/SegmentationMasks/combined_gt_stack1.mha,P002_1_FATFRACTION_stack1_dseg.nii.gz,0.715186,5.000000,0.556645,-0.396297,0.403091,4.287717e-05,0.006391,0.0,0.0,0.783211
46,P002_1/SegmentationMasks/combined_gt_stack2.mha,P002_1_FATFRACTION_stack2_dseg.nii.gz,0.697471,8.062258,0.535475,0.360913,0.148952,8.232156e-04,0.032385,0.0,0.0,0.931784
47,P002_1/SegmentationMasks/combined_gt_stack3.mha,P002_1_FATFRACTION_stack3_dseg.nii.gz,0.682299,12.041595,0.517795,-0.211243,0.382882,1.288962e-04,0.008756,0.0,0.0,0.848681
48,P003_1/SegmentationMasks/combined_gt_stack1.mha,P003_1_FATFRACTION_stack1_dseg.nii.gz,0.608677,13.638182,0.437480,-0.781772,0.562382,3.819329e-07,0.008561,0.0,0.0,0.793261
49,P003_1/SegmentationMasks/combined_gt_stack2.mha,P003_1_FATFRACTION_stack2_dseg.nii.gz,0.742826,5.916080,0.590870,-0.505352,0.407008,6.369107e-06,0.017028,0.0,0.0,0.884581
50,P003_1/SegmentationMasks/combined_gt_stack3.mha,P003_1_FATFRACTION_stack3_dseg.nii.gz,0.618741,10.099505,0.447955,-0.760948,0.551791,6.364947e-07,0.008090,0.0,0.0,0.845496
51,P004_1/SegmentationMasks/combined_gt_stack1.mha,P004_1_FATFRACTION_stack1_dseg.nii.gz,0.701729,7.348469,0.540511,-0.056012,0.317388,3.372699e-04,0.019526,0.0,0.0,0.859494
52,P004_1/SegmentationMasks/combined_gt_stack2.mha,P004_1_FATFRACTION_stack2_dseg.nii.gz,0.709701,7.141428,0.550029,-0.038608,0.303739,2.805488e-04,0.016347,0.0,0.0,0.897460
53,P004_1/SegmentationMasks/combined_gt_stack3.mha,P004_1_FATFRACTION_stack3_dseg.nii.gz,0.077079,13.601471,0.040084,-1.440162,0.955189,6.358172e-06,0.000142,0.0,0.0,0.000000

## Left Sartorius  (GT label 4 · pred label 7141)

In [6]:
existing = pd.read_csv(os.path.join(CSV_IN, "df_l_sart_thigh.csv"), index_col=0)

extra_rows = []
for _, row in existing.iterrows():
    gt_path   = os.path.join(GT_BASE, row["image"])
    pred_path = os.path.join(PRED_DIR, row["pred_label"])

    gt_image      = sitk.ReadImage(gt_path)
    segment_image = sitk.ReadImage(pred_path)
    segment_image.CopyInformation(gt_image)

    gt   = sitk.Cast(gt_image      == 4,        sitk.sitkUInt8)
    pred = sitk.Cast(segment_image == 7141,  sitk.sitkUInt8)

    gt_arr   = sitk.GetArrayFromImage(gt).astype(float)
    pred_arr = sitk.GetArrayFromImage(pred).astype(float)

    bce      = binary_cross_entropy(gt_arr, pred_arr)
    biou     = boundary_iou_3d(BOUNDARY_DISTANCE, gt_arr, pred_arr)
    isd_pred = inter_slice_dice(pred_arr)
    isd_gt   = inter_slice_dice(gt_arr)

    extra_rows.append({
        "L_sartorius_binary_cross_entropy":  bce,
        "L_sartorius_boundary_iou_3d":       biou,
        "L_sartorius_inter_slice_dice_pred": isd_pred,
        "L_sartorius_inter_slice_dice_gt":   isd_gt,
    })

extra_df = pd.DataFrame(extra_rows, index=existing.index)
longer   = pd.concat([existing, extra_df], axis=1)
longer.to_csv(os.path.join(CSV_OUT, "df_l_sart_thigh_LONGER.csv"))
longer

,image,pred_label,L_sartor_lower_dice:,L_sartor_lower_Hausdorff:,L_sartor_jaccard,L_sartor_volume_similarity,L_sartor_falseNegative,L_sartor_falsePostivie,L_sartorius_binary_cross_entropy,L_sartorius_boundary_iou_3d,L_sartorius_inter_slice_dice_pred,L_sartorius_inter_slice_dice_gt
0,HV001_1/SegmentationMasks/combined_gt_stack1.mha,HV001_1_FATFRACTION_stack1_dseg.nii.gz,0.707466,67.601775,0.547348,0.439467,0.158762,0.000332,0.013738,0.0,0.0,0.860357
1,HV001_1/SegmentationMasks/combined_gt_stack2.mha,HV001_1_FATFRACTION_stack2_dseg.nii.gz,0.842695,16.309506,0.728153,0.439467,0.223898,0.000079,0.016196,0.0,0.0,0.851485
2,HV001_2/SegmentationMasks/combined_gt_stack1.mha,HV001_2_FATFRACTION_stack1_dseg.nii.gz,0.712279,57.175169,0.553131,0.439467,0.102808,0.000397,0.015628,0.0,0.0,0.875143
3,HV001_2/SegmentationMasks/combined_gt_stack2.mha,HV001_2_FATFRACTION_stack2_dseg.nii.gz,0.866341,8.000000,0.764199,0.439467,0.128428,0.000160,0.018557,0.0,0.0,0.865005
4,HV001_3/SegmentationMasks/combined_gt_stack1.mha,HV001_3_FATFRACTION_stack1_dseg.nii.gz,0.688084,67.742158,0.524488,0.439467,0.079907,0.000462,0.016523,0.0,0.0,0.868883
5,HV001_3/SegmentationMasks/combined_gt_stack2.mha,HV001_3_FATFRACTION_stack2_dseg.nii.gz,0.855911,8.000000,0.748115,0.439467,0.164032,0.000133,0.017359,0.0,0.0,0.862667
6,HV002_1/SegmentationMasks/combined_gt_stack1.mha,HV002_1_FATFRACTION_stack1_dseg.nii.gz,0.428490,125.769631,0.272661,0.439467,0.055848,0.001069,0.023817,0.0,0.0,0.871289
7,HV002_1/SegmentationMasks/combined_gt_stack2.mha,HV002_1_FATFRACTION_stack2_dseg.nii.gz,0.718408,15.297059,0.560559,0.439467,0.106041,0.000450,0.018161,0.0,0.0,0.877758
8,HV002_2/SegmentationMasks/combined_gt_stack1.mha,HV002_2_FATFRACTION_stack1_dseg.nii.gz,0.416969,133.465351,0.263399,0.439467,0.048201,0.001027,0.022583,0.0,0.0,0.872510
9,HV002_2/SegmentationMasks/combined_gt_stack2.mha,HV002_2_FATFRACTION_stack2_dseg.nii.gz,0.803378,10.049876,0.671371,0.439467,0.113024,0.000330,0.019981,0.0,0.0,0.883828
10,HV002_3/SegmentationMasks/combined_gt_stack1.mha,HV002_3_FATFRACTION_stack1_dseg.nii.gz,0.417536,131.369707,0.263852,0.439467,0.033883,0.001079,0.023693,0.0,0.0,0.883085
11,HV002_3/SegmentationMasks/combined_gt_stack2.mha,HV002_3_FATFRACTION_stack2_dseg.nii.gz,0.805121,12.083046,0.673810,0.439467,0.101134,0.000325,0.019336,0.0,0.0,0.888276
12,HV003_1/SegmentationMasks/combined_gt_stack1.mha,HV003_1_FATFRACTION_stack1_dseg.nii.gz,0.523249,86.498555,0.354325,0.439467,0.047526,0.000763,0.019221,0.0,0.0,0.888440
13,HV003_1/SegmentationMasks/combined_gt_stack2.mha,HV003_1_FATFRACTION_stack2_dseg.nii.gz,0.870028,8.246211,0.769956,0.439467,0.109774,0.000176,0.018980,0.0,0.0,0.874989
14,HV003_2/SegmentationMasks/combined_gt_stack1.mha,HV003_2_FATFRACTION_stack1_dseg.nii.gz,0.475259,96.963911,0.311698,0.439467,0.037978,0.000831,0.019570,0.0,0.0,0.882024
15,HV003_2/SegmentationMasks/combined_gt_stack2.mha,HV003_2_FATFRACTION_stack2_dseg.nii.gz,0.866934,7.000000,0.765122,0.439467,0.107155,0.000186,0.018996,0.0,0.0,0.874006
16,HV003_3/SegmentationMasks/combined_gt_stack1.mha,HV003_3_FATFRACTION_stack1_dseg.nii.gz,0.561551,90.338253,0.390387,0.439467,0.035463,0.000697,0.018590,0.0,0.0,0.881558
17,HV003_3/SegmentationMasks/combined_gt_stack2.mha,HV003_3_FATFRACTION_stack2_dseg.nii.gz,0.870887,8.000000,0.771302,0.439467,0.089412,0.000206,0.020062,0.0,0.0,0.877498
18,HV004_1/SegmentationMasks/combined_gt_stack1.mha,HV004_1_FATFRACTION_stack1_dseg.nii.gz,0.749476,73.979727,0.599329,0.439467,0.098257,0.000338,0.015153,0.0,0.0,0.860239
19,HV004_1/SegmentationMasks/combined_gt_stack2.mha,HV004_1_FATFRACTION_stack2_dseg.nii.gz,0.875125,8.000000,0.777975,0.439467,0.109060,0.000147,0.016910,0.0,0.0,0.880988
20,HV005_1/SegmentationMasks/combined_gt_stack1.mha,HV005_1_FATFRACTION_stack1_dseg.nii.gz,0.780082,61.131007,0.639455,0.439467,0.112753,0.000307,0.016247,0.0,0.0,0.866931
21,HV005_1/SegmentationMasks/combined_gt_stack2.mha,HV005_1_FATFRACTION_stack2_dseg.nii.gz,0.850796,12.000000,0.740334,0.439467,0.179882,0.000118,0.016360,0.0,0.0,0.881898
22,HV006_1/SegmentationMasks/combined_gt_stack1.mha,HV006_1_FATFRACTION_stack1_dseg.nii.gz,0.701429,57.349804,0.540155,0.439467,0.063136,0.000485,0.017763,0.0,0.0,0.881287
23,HV006_1/SegmentationMasks/combined_gt_stack2.mha,HV006_1_FATFRACTION_stack2_dseg.nii.gz,0.871026,5.099020,0.771520,0.439467,0.135298,0.000140,0.018407,0.0,0.0,0.883450
24,HV007_1/SegmentationMasks/combined_gt_stack1.mha,HV007_1_FATFRACTION_stack1_dseg.nii.gz,0.763220,46.184413,0.617103,0.439467,0.211265,0.000184,0.011347,0.0,0.0,0.850136
25,HV007_1/SegmentationMasks/combined_gt_stack2.mha,HV007_1_FATFRACTION_stack2_dseg.nii.gz,0.776671,12.409674,0.634883,0.439467,0.307954,0.000078,0.010900,0.0,0.0,0.849741
26,HV008_1/SegmentationMasks/combined_gt_stack1.mha,HV008_1_FATFRACTION_stack1_dseg.nii.gz,0.830691,42.237424,0.710411,0.439467,0.152326,0.000173,0.015013,0.0,0.0,0.856002
27,HV008_1/SegmentationMasks/combined_gt_stack2.mha,HV008_1_FATFRACTION_stack2_dseg.nii.gz,0.839892,6.000000,0.723978,0.439467,0.207570,0.000087,0.013100,0.0,0.0,0.878453
28,HV009_1/SegmentationMasks/combined_gt_stack1.mha,HV009_1_FATFRACTION_stack1_dseg.nii.gz,0.652036,52.735187,0.483720,0.439467,0.037550,0.000618,0.019640,0.0,0.0,0.880010
29,HV009_1/SegmentationMasks/combined_gt_stack2.mha,HV009_1_FATFRACTION_stack2_dseg.nii.gz,0.861423,8.062258,0.756578,0.439467,0.127427,0.000176,0.018926,0.0,0.0,0.883636
30,HV010_1/SegmentationMasks/combined_gt_stack1.mha,HV010_1_FATFRACTION_stack1_dseg.nii.gz,0.700333,53.637673,0.538856,0.439467,0.304625,0.000118,0.006462,0.0,0.0,0.809663
31,HV010_1/SegmentationMasks/combined_gt_stack2.mha,HV010_1_FATFRACTION_stack2_dseg.nii.gz,0.813376,6.480741,0.685453,0.439467,0.225909,0.000082,0.009214,0.0,0.0,0.822837
32,HV011_1/SegmentationMasks/combined_gt_stack1.mha,HV011_1_FATFRACTION_stack1_dseg.nii.gz,0.727193,49.284886,0.571330,0.439467,0.234668,0.000138,0.007242,0.0,0.0,0.821297
33,HV011_1/SegmentationMasks/combined_gt_stack2.mha,HV011_1_FATFRACTION_stack2_dseg.nii.gz,0.814290,5.000000,0.686753,0.439467,0.229553,0.000077,0.009101,0.0,0.0,0.822902
34,HV012_1/SegmentationMasks/combined_gt_stack1.mha,HV012_1_FATFRACTION_stack1_dseg.nii.gz,0.583178,56.071383,0.411610,0.439467,0.477529,0.000168,0.007973,0.0,0.0,0.887428
35,HV012_1/SegmentationMasks/combined_gt_stack2.mha,HV012_1_FATFRACTION_stack2_dseg.nii.gz,0.577656,8.602325,0.406129,0.439467,0.591013,0.000011,0.010777,0.0,0.0,0.845467
36,HV013_1/SegmentationMasks/combined_gt_stack1.mha,HV013_1_FATFRACTION_stack1_dseg.nii.gz,0.580337,52.649786,0.408785,0.439467,0.523190,0.000160,0.009957,0.0,0.0,0.872810
37,HV013_1/SegmentationMasks/combined_gt_stack2.mha,HV013_1_FATFRACTION_stack2_dseg.nii.gz,0.607341,20.024984,0.436101,0.439467,0.563192,0.000002,0.010822,0.0,0.0,0.847004
38,HV014_1/SegmentationMasks/combined_gt_stack1.mha,HV014_1_FATFRACTION_stack1_dseg.nii.gz,0.591415,58.249464,0.419865,0.439467,0.536100,0.000116,0.010103,0.0,0.0,0.850106
39,HV014_1/SegmentationMasks/combined_gt_stack2.mha,HV014_1_FATFRACTION_stack2_dseg.nii.gz,0.606400,8.944272,0.435132,0.439467,0.561483,0.000010,0.009083,0.0,0.0,0.811414
40,HV015_1/SegmentationMasks/combined_gt_stack1.mha,HV015_1_FATFRACTION_stack1_dseg.nii.gz,0.635032,60.340699,0.465236,0.439467,0.468185,0.000178,0.013552,0.0,0.0,0.850750
41,HV015_1/SegmentationMasks/combined_gt_stack2.mha,HV015_1_FATFRACTION_stack2_dseg.nii.gz,0.600667,16.401219,0.429253,0.439467,0.569535,0.000005,0.012022,0.0,0.0,0.865719
42,P001_1/SegmentationMasks/combined_gt_stack1.mha,P001_1_FATFRACTION_stack1_dseg.nii.gz,0.242986,51.701064,0.138295,0.439467,0.201801,0.002292,0.043106,0.0,0.0,0.905711
43,P001_1/SegmentationMasks/combined_gt_stack2.mha,P001_1_FATFRACTION_stack2_dseg.nii.gz,0.480618,23.409400,0.316324,0.439467,0.131954,0.001512,0.036475,0.0,0.0,0.917611
44,P001_1/SegmentationMasks/combined_gt_stack3.mha,P001_1_FATFRACTION_stack3_dseg.nii.gz,0.688464,16.643317,0.524930,0.439467,0.093190,0.000708,0.025627,0.0,0.0,0.895310
45,P002_1/SegmentationMasks/combined_gt_stack1.mha,P002_1_FATFRACTION_stack1_dseg.nii.gz,0.719174,12.083046,0.561493,0.439467,0.274934,0.000310,0.017419,0.0,0.0,0.922114
46,P002_1/SegmentationMasks/combined_gt_stack2.mha,P002_1_FATFRACTION_stack2_dseg.nii.gz,0.723001,6.324555,0.566172,0.439467,0.402624,0.000080,0.015189,0.0,0.0,0.854369
47,P002_1/SegmentationMasks/combined_gt_stack3.mha,P002_1_FATFRACTION_stack3_dseg.nii.gz,0.640990,10.677078,0.471660,0.439467,0.527688,0.000002,0.010537,0.0,0.0,0.865971
48,P003_1/SegmentationMasks/combined_gt_stack1.mha,P003_1_FATFRACTION_stack1_dseg.nii.gz,0.710682,7.348469,0.551208,0.439467,0.343473,0.000236,0.016847,0.0,0.0,0.838502
49,P003_1/SegmentationMasks/combined_gt_stack2.mha,P003_1_FATFRACTION_stack2_dseg.nii.gz,0.723373,6.403124,0.566628,0.439467,0.418895,0.000046,0.017714,0.0,0.0,0.846885
50,P003_1/SegmentationMasks/combined_gt_stack3.mha,P003_1_FATFRACTION_stack3_dseg.nii.gz,0.766159,11.180340,0.620954,0.439467,0.246880,0.000239,0.017450,0.0,0.0,0.910627
51,P004_1/SegmentationMasks/combined_gt_stack1.mha,P004_1_FATFRACTION_stack1_dseg.nii.gz,0.786051,7.211103,0.647516,0.439467,0.318741,0.000082,0.018575,0.0,0.0,0.872133
52,P004_1/SegmentationMasks/combined_gt_stack2.mha,P004_1_FATFRACTION_stack2_dseg.nii.gz,0.788392,5.196152,0.650698,0.439467,0.333037,0.000039,0.017532,0.0,0.0,0.870019
53,P004_1/SegmentationMasks/combined_gt_stack3.mha,P004_1_FATFRACTION_stack3_dseg.nii.gz,0.797187,6.633250,0.662769,0.439467,0.245276,0.000098,0.010176,0.0,0.0,0.871962

## Right Sartorius  (GT label 8 · pred label 7142)

In [7]:
existing = pd.read_csv(os.path.join(CSV_IN, "df_r_sart_thigh.csv"), index_col=0)

extra_rows = []
for _, row in existing.iterrows():
    gt_path   = os.path.join(GT_BASE, row["image"])
    pred_path = os.path.join(PRED_DIR, row["pred_label"])

    gt_image      = sitk.ReadImage(gt_path)
    segment_image = sitk.ReadImage(pred_path)
    segment_image.CopyInformation(gt_image)

    gt   = sitk.Cast(gt_image      == 8,        sitk.sitkUInt8)
    pred = sitk.Cast(segment_image == 7142,  sitk.sitkUInt8)

    gt_arr   = sitk.GetArrayFromImage(gt).astype(float)
    pred_arr = sitk.GetArrayFromImage(pred).astype(float)

    bce      = binary_cross_entropy(gt_arr, pred_arr)
    biou     = boundary_iou_3d(BOUNDARY_DISTANCE, gt_arr, pred_arr)
    isd_pred = inter_slice_dice(pred_arr)
    isd_gt   = inter_slice_dice(gt_arr)

    extra_rows.append({
        "R_sartorius_binary_cross_entropy":  bce,
        "R_sartorius_boundary_iou_3d":       biou,
        "R_sartorius_inter_slice_dice_pred": isd_pred,
        "R_sartorius_inter_slice_dice_gt":   isd_gt,
    })

extra_df = pd.DataFrame(extra_rows, index=existing.index)
longer   = pd.concat([existing, extra_df], axis=1)
longer.to_csv(os.path.join(CSV_OUT, "df_r_sart_thigh_LONGER.csv"))
longer

,image,pred_label,R_sartorius_lower_dice:,R_sartorius_lower_Hausdorff:,R_sartorius_jaccard,R_sartorius_volume_similarity,R_sartorius_falseNegative,R_sartorius_falsePostivie,R_sartorius_binary_cross_entropy,R_sartorius_boundary_iou_3d,R_sartorius_inter_slice_dice_pred,R_sartorius_inter_slice_dice_gt
0,HV001_1/SegmentationMasks/combined_gt_stack1.mha,HV001_1_FATFRACTION_stack1_dseg.nii.gz,0.605258,55.686623,0.433957,0.391133,0.247598,4.321017e-04,0.014097,0.0,0.0,0.815539
1,HV001_1/SegmentationMasks/combined_gt_stack2.mha,HV001_1_FATFRACTION_stack2_dseg.nii.gz,0.787171,16.000000,0.649037,-0.310225,0.318533,6.129960e-05,0.014446,0.0,0.0,0.787003
2,HV001_2/SegmentationMasks/combined_gt_stack1.mha,HV001_2_FATFRACTION_stack1_dseg.nii.gz,0.624992,55.398556,0.454537,0.510552,0.160774,4.830548e-04,0.015498,0.0,0.0,0.832135
3,HV001_2/SegmentationMasks/combined_gt_stack2.mha,HV001_2_FATFRACTION_stack2_dseg.nii.gz,0.877761,12.000000,0.782152,-0.115869,0.170307,7.313538e-05,0.017249,0.0,0.0,0.844545
4,HV001_3/SegmentationMasks/combined_gt_stack1.mha,HV001_3_FATFRACTION_stack1_dseg.nii.gz,0.491179,104.249700,0.325538,0.864257,0.135053,7.071128e-04,0.017339,0.0,0.0,0.866700
5,HV001_3/SegmentationMasks/combined_gt_stack2.mha,HV001_3_FATFRACTION_stack2_dseg.nii.gz,0.880810,16.000000,0.787006,-0.048889,0.140208,1.089882e-04,0.018067,0.0,0.0,0.851053
6,HV002_1/SegmentationMasks/combined_gt_stack1.mha,HV002_1_FATFRACTION_stack1_dseg.nii.gz,0.709546,37.854986,0.549843,0.423433,0.099884,5.819717e-04,0.022614,0.0,0.0,0.872423
7,HV002_1/SegmentationMasks/combined_gt_stack2.mha,HV002_1_FATFRACTION_stack2_dseg.nii.gz,0.854907,20.199010,0.746583,0.005774,0.142618,1.699353e-04,0.018542,0.0,0.0,0.872628
8,HV002_2/SegmentationMasks/combined_gt_stack1.mha,HV002_2_FATFRACTION_stack1_dseg.nii.gz,0.713230,38.884444,0.554279,0.291399,0.165130,4.379835e-04,0.018686,0.0,0.0,0.854515
9,HV002_2/SegmentationMasks/combined_gt_stack2.mha,HV002_2_FATFRACTION_stack2_dseg.nii.gz,0.867781,12.000000,0.766442,-0.056842,0.156201,1.258435e-04,0.018962,0.0,0.0,0.872827
10,HV002_3/SegmentationMasks/combined_gt_stack1.mha,HV002_3_FATFRACTION_stack1_dseg.nii.gz,0.745359,40.718546,0.594081,0.213227,0.165693,3.941431e-04,0.019441,0.0,0.0,0.872335
11,HV002_3/SegmentationMasks/combined_gt_stack2.mha,HV002_3_FATFRACTION_stack2_dseg.nii.gz,0.877700,12.165525,0.782054,-0.134883,0.177754,6.306788e-05,0.017259,0.0,0.0,0.871347
12,HV003_1/SegmentationMasks/combined_gt_stack1.mha,HV003_1_FATFRACTION_stack1_dseg.nii.gz,0.739017,43.278170,0.586064,0.415570,0.067150,4.725953e-04,0.019611,0.0,0.0,0.882661
13,HV003_1/SegmentationMasks/combined_gt_stack2.mha,HV003_1_FATFRACTION_stack2_dseg.nii.gz,0.898156,16.000000,0.815139,-0.032679,0.116284,9.985346e-05,0.018494,0.0,0.0,0.879116
14,HV003_2/SegmentationMasks/combined_gt_stack1.mha,HV003_2_FATFRACTION_stack1_dseg.nii.gz,0.731323,47.212287,0.576446,0.335065,0.121499,4.165751e-04,0.017957,0.0,0.0,0.868047
15,HV003_2/SegmentationMasks/combined_gt_stack2.mha,HV003_2_FATFRACTION_stack2_dseg.nii.gz,0.905358,20.000000,0.827081,-0.028810,0.107499,9.356620e-05,0.018503,0.0,0.0,0.875949
16,HV003_3/SegmentationMasks/combined_gt_stack1.mha,HV003_3_FATFRACTION_stack1_dseg.nii.gz,0.738143,43.874822,0.584966,0.197888,0.180802,3.250008e-04,0.015943,0.0,0.0,0.866518
17,HV003_3/SegmentationMasks/combined_gt_stack2.mha,HV003_3_FATFRACTION_stack2_dseg.nii.gz,0.885740,16.000000,0.794914,-0.136298,0.170771,5.122830e-05,0.016667,0.0,0.0,0.866449
18,HV004_1/SegmentationMasks/combined_gt_stack1.mha,HV004_1_FATFRACTION_stack1_dseg.nii.gz,0.752834,73.443856,0.603636,0.201106,0.163004,2.980531e-04,0.015194,0.0,0.0,0.849464
19,HV004_1/SegmentationMasks/combined_gt_stack2.mha,HV004_1_FATFRACTION_stack2_dseg.nii.gz,0.882165,12.000000,0.789172,-0.072150,0.148552,8.147139e-05,0.015466,0.0,0.0,0.859167
20,HV005_1/SegmentationMasks/combined_gt_stack1.mha,HV005_1_FATFRACTION_stack1_dseg.nii.gz,0.729471,51.633323,0.574147,0.049727,0.251930,2.274390e-04,0.012709,0.0,0.0,0.833693
21,HV005_1/SegmentationMasks/combined_gt_stack2.mha,HV005_1_FATFRACTION_stack2_dseg.nii.gz,0.826702,9.899495,0.704597,-0.114058,0.217900,1.033152e-04,0.013493,0.0,0.0,0.865018
22,HV006_1/SegmentationMasks/combined_gt_stack1.mha,HV006_1_FATFRACTION_stack1_dseg.nii.gz,0.754273,55.398556,0.605488,0.161152,0.179625,2.642586e-04,0.014095,0.0,0.0,0.865698
23,HV006_1/SegmentationMasks/combined_gt_stack2.mha,HV006_1_FATFRACTION_stack2_dseg.nii.gz,0.877635,7.211103,0.781952,-0.108748,0.167624,7.111445e-05,0.015924,0.0,0.0,0.866174
24,HV007_1/SegmentationMasks/combined_gt_stack1.mha,HV007_1_FATFRACTION_stack1_dseg.nii.gz,0.782739,49.658836,0.643034,0.024297,0.207635,1.638469e-04,0.011643,0.0,0.0,0.844036
25,HV007_1/SegmentationMasks/combined_gt_stack2.mha,HV007_1_FATFRACTION_stack2_dseg.nii.gz,0.824859,7.280110,0.701924,-0.214532,0.255049,5.469947e-05,0.011586,0.0,0.0,0.841450
26,HV008_1/SegmentationMasks/combined_gt_stack1.mha,HV008_1_FATFRACTION_stack1_dseg.nii.gz,0.796531,36.715120,0.661863,-0.026418,0.213853,1.701881e-04,0.014214,0.0,0.0,0.854620
27,HV008_1/SegmentationMasks/combined_gt_stack2.mha,HV008_1_FATFRACTION_stack2_dseg.nii.gz,0.849612,6.708204,0.738544,-0.185196,0.222392,5.087306e-05,0.012863,0.0,0.0,0.862274
28,HV009_1/SegmentationMasks/combined_gt_stack1.mha,HV009_1_FATFRACTION_stack1_dseg.nii.gz,0.753047,50.616203,0.603910,0.341663,0.091804,3.961486e-04,0.017880,0.0,0.0,0.865113
29,HV009_1/SegmentationMasks/combined_gt_stack2.mha,HV009_1_FATFRACTION_stack2_dseg.nii.gz,0.884360,12.206556,0.792694,-0.050628,0.137474,1.047162e-04,0.018191,0.0,0.0,0.869482
30,HV010_1/SegmentationMasks/combined_gt_stack1.mha,HV010_1_FATFRACTION_stack1_dseg.nii.gz,0.709641,38.742741,0.549956,-0.101939,0.324775,8.707731e-05,0.005562,0.0,0.0,0.833566
31,HV010_1/SegmentationMasks/combined_gt_stack2.mha,HV010_1_FATFRACTION_stack2_dseg.nii.gz,0.821460,4.242641,0.697014,-0.246496,0.268675,2.807723e-05,0.007172,0.0,0.0,0.802485
32,HV011_1/SegmentationMasks/combined_gt_stack1.mha,HV011_1_FATFRACTION_stack1_dseg.nii.gz,0.728326,35.156792,0.572730,-0.112927,0.310600,7.787540e-05,0.005501,0.0,0.0,0.845227
33,HV011_1/SegmentationMasks/combined_gt_stack2.mha,HV011_1_FATFRACTION_stack2_dseg.nii.gz,0.833046,5.000000,0.713864,-0.223498,0.250688,2.832266e-05,0.007341,0.0,0.0,0.799151
34,HV012_1/SegmentationMasks/combined_gt_stack1.mha,HV012_1_FATFRACTION_stack1_dseg.nii.gz,0.603830,56.329388,0.432490,-0.093465,0.423129,1.974381e-04,0.008676,0.0,0.0,0.873919
35,HV012_1/SegmentationMasks/combined_gt_stack2.mha,HV012_1_FATFRACTION_stack2_dseg.nii.gz,0.574572,7.810250,0.403087,-0.824489,0.593150,1.381008e-05,0.009909,0.0,0.0,0.831658
36,HV013_1/SegmentationMasks/combined_gt_stack1.mha,HV013_1_FATFRACTION_stack1_dseg.nii.gz,0.696100,48.928519,0.533860,-0.305617,0.396170,1.223363e-04,0.011046,0.0,0.0,0.874055
37,HV013_1/SegmentationMasks/combined_gt_stack2.mha,HV013_1_FATFRACTION_stack2_dseg.nii.gz,0.689864,20.099751,0.526560,-0.610911,0.471553,5.365160e-06,0.012815,0.0,0.0,0.846840
38,HV014_1/SegmentationMasks/combined_gt_stack1.mha,HV014_1_FATFRACTION_stack1_dseg.nii.gz,0.506329,54.267854,0.338983,-0.790436,0.637097,7.299209e-05,0.007220,0.0,0.0,0.797583
39,HV014_1/SegmentationMasks/combined_gt_stack2.mha,HV014_1_FATFRACTION_stack2_dseg.nii.gz,0.000000,76.419893,0.000000,-1.515178,1.000000,1.665700e-04,0.002682,0.0,0.0,0.068704
40,HV015_1/SegmentationMasks/combined_gt_stack1.mha,HV015_1_FATFRACTION_stack1_dseg.nii.gz,0.582959,72.173402,0.411392,-0.403851,0.514979,2.308529e-04,0.013787,0.0,0.0,0.860448
41,HV015_1/SegmentationMasks/combined_gt_stack2.mha,HV015_1_FATFRACTION_stack2_dseg.nii.gz,0.694640,9.219544,0.532145,-0.536410,0.452265,4.839330e-05,0.015338,0.0,0.0,0.844281
42,P001_1/SegmentationMasks/combined_gt_stack1.mha,P001_1_FATFRACTION_stack1_dseg.nii.gz,0.791661,11.224972,0.655165,-0.113364,0.250805,3.068477e-04,0.030698,0.0,0.0,0.862577
43,P001_1/SegmentationMasks/combined_gt_stack2.mha,P001_1_FATFRACTION_stack2_dseg.nii.gz,0.853000,11.000000,0.743679,-0.046926,0.166555,2.757956e-04,0.035059,0.0,0.0,0.903661
44,P001_1/SegmentationMasks/combined_gt_stack3.mha,P001_1_FATFRACTION_stack3_dseg.nii.gz,0.320253,24.939928,0.190656,1.237131,0.160398,1.174187e-03,0.023586,0.0,0.0,0.906856
45,P002_1/SegmentationMasks/combined_gt_stack1.mha,P002_1_FATFRACTION_stack1_dseg.nii.gz,0.736528,6.480741,0.582940,-0.264963,0.349634,1.285709e-04,0.013709,0.0,0.0,0.914140
46,P002_1/SegmentationMasks/combined_gt_stack2.mha,P002_1_FATFRACTION_stack2_dseg.nii.gz,0.745660,4.472136,0.594464,-0.475712,0.397620,1.795325e-05,0.013361,0.0,0.0,0.856230
47,P002_1/SegmentationMasks/combined_gt_stack3.mha,P002_1_FATFRACTION_stack3_dseg.nii.gz,0.561356,12.083046,0.390198,-0.876720,0.609725,2.546414e-07,0.008114,0.0,0.0,0.835799
48,P003_1/SegmentationMasks/combined_gt_stack1.mha,P003_1_FATFRACTION_stack1_dseg.nii.gz,0.684076,7.483315,0.519845,-0.474836,0.447174,9.206762e-05,0.014394,0.0,0.0,0.813119
49,P003_1/SegmentationMasks/combined_gt_stack2.mha,P003_1_FATFRACTION_stack2_dseg.nii.gz,0.739814,5.099020,0.587067,-0.464480,0.399619,4.395404e-05,0.019425,0.0,0.0,0.854076
50,P003_1/SegmentationMasks/combined_gt_stack3.mha,P003_1_FATFRACTION_stack3_dseg.nii.gz,0.759316,6.324555,0.612014,-0.430039,0.375058,3.451574e-05,0.016989,0.0,0.0,0.914644
51,P004_1/SegmentationMasks/combined_gt_stack1.mha,P004_1_FATFRACTION_stack1_dseg.nii.gz,0.784718,13.747727,0.645709,-0.321753,0.324030,7.999063e-05,0.019852,0.0,0.0,0.844290
52,P004_1/SegmentationMasks/combined_gt_stack2.mha,P004_1_FATFRACTION_stack2_dseg.nii.gz,0.677465,9.055385,0.512248,-0.131482,0.364325,2.754814e-04,0.016136,0.0,0.0,0.860517
53,P004_1/SegmentationMasks/combined_gt_stack3.mha,P004_1_FATFRACTION_stack3_dseg.nii.gz,0.619211,18.788294,0.448447,0.439467,0.206411,2.779375e-04,0.009096,0.0,0.0,0.845014